Load script/style asynchronously.
abpframework/abp pull request #10317
Opened 2021-10-14 04:52 UTC by maliming

Resolve #10306

```cs
<abp-script defer="true" src="/Pages/Index.js" />

<abp-script-bundle defer="true">
    <abp-script src="/Pages/Index.js" />
</abp-script-bundle>

Configure<AbpTagHelperScriptStyleLoadingOptions>(options =>
{
    options.PreloadStyles.Add("/__bundles/Basic.Global");
});
```

2021-10-24 13:04 UTC, hikalkan requested changes

2021-10-24 13:04 UTC, hikalkan commented on framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bundling/Volo/Abp/AspNetCore/Mvc/UI/Bundling/TagHelpers/AbpTagHelperScriptStyleLoadingOptions.cs
> +        public bool GlobalPreloadStyle { get; set; }
`GlobalPreloadStyle` is not a good name for a boolean. We can rename it to `PreloadStylesByDefault`.

2021-10-24 13:04 UTC, hikalkan commented on framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bundling/Volo/Abp/AspNetCore/Mvc/UI/Bundling/TagHelpers/AbpTagHelperScriptStyleLoadingOptions.cs
> +    public class AbpTagHelperScriptStyleLoadingOptions
I think we can remove this class (I didn't like the name much), and move options to `AbpBundlingOptions.cs`.

2021-10-24 13:04 UTC, hikalkan commented on framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bundling/Volo/Abp/AspNetCore/Mvc/UI/Bundling/TagHelpers/AbpTagHelperScriptStyleLoadingOptions.cs
> +        public bool GlobalDeferScript { get; set; }
We can rename this to `DeferScriptsByDefault`.

2021-10-24 13:04 UTC, hikalkan commented
Please create an issue about the documentation update and send a PR for it separately.

2021-10-25 05:49 UTC, realLiangshiwei approved these changes

2021-10-25 05:54 UTC, hikalkan approved these changes

2021-10-25 05:54 UTC, merged