Introduce DynamicJavaScriptProxyOptions
abpframework/abp pull request #10370
Opened 2021-10-20 08:27 UTC by realLiangshiwei

Resolve https://github.com/abpframework/abp/issues/9955, https://github.com/abpframework/abp/issues/10419

I used disabled mode, dynamic proxy is enabled by default, we manually disable it in the module. 

For developers, they don’t need to change anything when they upgrade to 5.0, the dynamic proxy is still works.

2021-10-24 13:14 UTC, hikalkan requested changes

2021-10-24 13:14 UTC, hikalkan commented on framework/src/Volo.Abp.Http/Volo/Abp/Http/ProxyScripting/Generators/JQuery/DynamicJavaScriptProxyOptions.cs
> +        public bool EnabledAllModules { get; set; }
```suggestion
        public bool IsEnabledForAllModules { get; set; }
```

2021-10-24 13:14 UTC, hikalkan commented on framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/AbpCliCoreModule.cs
> +                options.EnabledAllModules = true;
I didn't understand why CLI enables it for all modules? Isn't that a server-side option?

2021-10-24 13:14 UTC, hikalkan commented on framework/src/Volo.Abp.Http/Volo/Abp/Http/ProxyScripting/Generators/JQuery/JQueryProxyScriptGenerator.cs
> +            if (_dynamicJavaScriptProxyOptions.EnabledModules.Any(m => m.Equals(module.Key, StringComparison.CurrentCultureIgnoreCase)))
I think we can make `_dynamicJavaScriptProxyOptions.EnabledModules` a HashSet<string> for a faster comparison. Also, we can force to be case-sensitive to make it even faster.

2021-10-24 13:14 UTC, hikalkan commented on modules/account/src/Volo.Abp.Account.HttpApi/Volo/Abp/Account/ProfileController.cs
> +    [Route("/api/account/my-profile")]
I think that's a breaking change. Can you create an issue with a `breaking-change` label to announce that.

2021-10-24 13:15 UTC, hikalkan commented
We are also moving the profile service from identity to account. I think you're doing that because the UI is in the account part, right? Please create an annoucement about that breaking change and the reason. Can you also make same for the abp-commercial? Thanks.

2021-10-25 07:23 UTC, realLiangshiwei commented on modules/account/src/Volo.Abp.Account.HttpApi/Volo/Abp/Account/ProfileController.cs
> +    [Route("/api/account/my-profile")]
https://github.com/abpframework/abp/issues/10419

2021-10-25 10:56 UTC, hikalkan approved these changes

2021-10-25 10:56 UTC, merged