Cms-Kit: Allow to write global css/js
abpframework/abp pull request #11705
Opened 2022-02-25 08:40 UTC by yekalkan

Resolves https://github.com/abpframework/abp/issues/11690

![image](https://user-images.githubusercontent.com/5793291/155682994-2b8acd20-c631-41f3-9e21-7d43006a066d.png)

2022-03-03 05:15 UTC, hikalkan commented
@yekalkan please help to @gizemmutukurt to test this.

2022-03-03 06:03 UTC, hikalkan requested changes

2022-03-03 06:03 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.Admin.Application.Contracts/Volo/CmsKit/Permissions/CmsKitAdminPermissions.cs
> +        public const string Default = GroupName + ".Menus";
```suggestion
        public const string Default = GroupName + ".GlobalResources";
```

2022-03-03 06:03 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.Admin.HttpApi.Client/ClientProxies/GlobalResourcesAdminClientProxy.cs
> +﻿// This file is part of GlobalResourcesAdminClientProxy, you can customize it here
Is this file accidently added? There is `GlobalResourceAdminClientProxy` above.

2022-03-03 06:03 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.EntityFrameworkCore/Volo/CmsKit/GlobalResources/EfCoreGlobalResourceRepository.cs
> +    public Task<GlobalResource> FindByName(string name,
```suggestion
    public Task<GlobalResource> FindByNameAsync(string name,
```

2022-03-03 06:03 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.MongoDB/Volo/CmsKit/MongoDB/GlobalResources/MongoGlobalResourceRepository.cs
> +    public Task<GlobalResource> FindByName(string name,
```suggestion
    public Task<GlobalResource> FindByNameAsync(string name,
```

2022-03-03 06:03 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.Public.Web/Pages/CmsKit/Shared/Components/GlobalResources/Script/Default.cshtml
> +﻿<script src="/global-resources/script"></script>
`/global-resources/script` is too common. change to `/cms-kit/global-resources/script`. Also, I didn't see, which controller matches this URL?

2022-03-03 06:03 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.Public.Web/Pages/CmsKit/Shared/Components/GlobalResources/Style/Default.cshtml
> +﻿<link rel="stylesheet" href="/global-resources/style"/>
`/global-resources/style` is too common. change to `/cms-kit/global-resources/style` .

2022-03-03 06:03 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.Admin.Web/Pages/CmsKit/GlobalResources/index.js
> +    $('#SaveResourcesButton').on('click','',function(){
If we have a single save button, why we have separate service methods (`setGlobalStyle` and `setGlobalScript`), and we have only one method for get.
I think this is not consistent. Unify these two methods into a single method and make a single AJAX call.

2022-03-03 07:14 UTC, hikalkan approved these changes

2022-03-03 07:14 UTC, hikalkan commented
@gizemmutukurt that's OK for me. Please you visually test and merge.

2022-03-04 08:44 UTC, gizemmutukurt approved these changes

2022-03-04 08:44 UTC, merged

2022-03-04 09:54 UTC, gizemmutukurt commented
Test is OK.