allow to remove cover photo of post
abpframework/abp pull request #12064
Opened 2022-03-23 19:36 UTC by demirmusa

closes #11962

2022-03-24 00:40 UTC, rqx110 commented on modules/cms-kit/src/Volo.CmsKit.Admin.Web/Pages/CmsKit/BlogPosts/update.js
> +                    debugger;
delete this line

2022-03-25 10:16 UTC, enisn commented on modules/cms-kit/src/Volo.CmsKit.Admin.HttpApi/Volo/CmsKit/Admin/Blogs/BlogPostAdminController.cs
> +    [Route("removeCoverImage/{id}")]
most of times, PascalCase naming is not a good approach in URLs, maybe we can do it as `remove-cover-image` or just a **DELETE** request to `{post-id}/cover-image/`

2022-03-25 10:18 UTC, enisn commented on modules/cms-kit/src/Volo.CmsKit.Admin.HttpApi/Volo/CmsKit/Admin/Blogs/BlogPostAdminController.cs
> +    [Route("removeCoverImage/{id}")]
The second looks better I think. `DELETE | .../blog-posts/123/cover-image` that request explains everything well.

what do you think?

```suggestion
    [Route("{id}/cover-image")]
```

2022-03-25 10:18 UTC, enisn commented on modules/cms-kit/src/Volo.CmsKit.Admin.HttpApi/Volo/CmsKit/Admin/Blogs/BlogPostAdminController.cs
> +    [Route("removeCoverImage/{id}")]
This changes requires re-generation of client-proxies

2022-03-25 10:20 UTC, enisn requested changes
Everything looks great but Route, I've suggested some alternatives for route of endpoint

2022-03-25 14:38 UTC, demirmusa commented
This pr's branch is opened using wrong base branch. I will reopened it with dev branch

2022-03-25 14:38 UTC, closed without merging