Index.md full translation to the Persian
abpframework/abp pull request #12160
Opened 2022-04-04 13:21 UTC by mheidari988

Created "fa" folder inside "docs" folder as per convention.
Created a copy of "images" folder from "en" to the "fa".
Translated and added "Index.md" Farsi aka Persian language version.

2022-04-12 21:28 UTC, hikalkan commented
Thanks a lot for your contribution. As stated in the contribution document;

>There are some fundamental documents need to be translated before publishing a language on the [ABP documentation web site](https://docs.abp.io/):

* Index (Home)
* Getting Started
* Web Application Development Tutorial

I see the last item is missing in this translation. We can accept the new language if you can complete this translation. Thanks a lot. See the contribution guide: https://docs.abp.io/en/abp/latest/Contribution/Index#document-translation

2022-04-12 21:49 UTC, mheidari988 commented
Sure, I'm working on it. RTL languages have pain with technical documentation, But I think I can finish it soon.

2022-05-18 12:58 UTC, RezaPouya commented
Thanks a lot . 
Do you need any help ?  
We are using abp in our project for over a year now , and we translated most of the resources for modules for ourselves .
so I have a question , are you working on translating the resources !? if yes , do you need any help !? if not , I can work on it . @hikalkan  @mheidari988

2022-05-21 04:35 UTC, ashkandehnavi commented on docs/fa/Getting-Started-AspNetCore-Application.md
> +کد منبع پروژه نمونه ایجاد شده در این آموزش را از [here](https://github.com/abpframework/abp-samples/tree/master/BasicAspNetCoreApplication).
better using "اینجا" for "here"

2022-05-21 04:54 UTC, ashkandehnavi commented on docs/fa/Getting-Started-Create-Solution.md
> +* `--tiered` با استفاده از این گذینه میتوانید از مدل چند لایه استفاده نمایید که لایه Authentıcatıon، لایه API و واست کاربری مجزا باشند.
`--tiered` با استفاده از این گزینه میتوانید از مدل چند لایه استفاده نمایید که لایه Authentıcatıon، لایه API و رابط کاربری به صورت فیزیکی مجزا باشند.

2022-05-21 05:06 UTC, ashkandehnavi commented on docs/fa/Getting-Started-Create-Solution.md
> +جهت استفاده از ساختار های [React Native](https://reactnative.dev/) در پروژه خود از دستور  `-m react-native` (و یا `--mobile react-native`) استفاده نمایید. این دستور اجازه میدهد تمپلیت اولیه مربوط به
جهت استفاده از ساختار های [React Native](https://reactnative.dev/) در پروژه خود از دستور  <span dir="ltr">`-m react-native` </span> (و یا <span dir="ltr">`--mobile react-native`</span>) استفاده نمایید. این دستور اجازه میدهد تمپلیت اولیه مربوط به ری اکت نیتیو مناسب تولید نرم افزار های تحت موبایل به پروژه اضافه شود

2022-05-21 07:50 UTC, ashkandehnavi requested changes
hi,
please use `<span dir="ltr">left to right text</span>` example: `<span dir="ltr">.IdentityServer</span>` or `<span dir="ltr">-dbms MySQL</span>` if do not using, in rtl view clutter of texts.

2022-05-21 09:22 UTC, mheidari988 commented
> Thanks a lot . Do you need any help ? We are using abp in our project for over a year now , and we translated most of the resources for modules for ourselves . so I have a question , are you working on translating the resources !? if yes , do you need any help !? if not , I can work on it . @hikalkan @mheidari988

Great,
Reference to [Contribution Guide](https://docs.abp.io/en/abp/latest/Contribution/Index#contribution-guide) and @hikalkan's [comment ](https://github.com/abpframework/abp/pull/12160#issuecomment-1097237212) there is two way to contribute which I believe if we can translate some documents, may be a great way to help Iranian developers to leverage the power of ABP Framework.

- [Resource Localization](https://docs.abp.io/en/abp/latest/Contribution/Index#resource-localization) is essential if anyone tries to use full feature ABP in Farsi language aka `Persian`, and I am currently working on it and I can share `abp-translate.json` so we split the task and make it done sone. By the way any help is appreciated.
-  Second is about [Document Translation](https://docs.abp.io/en/abp/latest/Contribution/Index#document-translation), which we need to translate `Web Application Development Tutorial` too.

By the way, I believe it is much better if we discuss these on ABP's official discord community. (my discord mohi#4787)

2022-05-21 09:31 UTC, mheidari988 commented on docs/fa/Getting-Started-AspNetCore-Application.md
> +کد منبع پروژه نمونه ایجاد شده در این آموزش را از [here](https://github.com/abpframework/abp-samples/tree/master/BasicAspNetCoreApplication).
done

2022-05-21 09:51 UTC, mheidari988 commented on docs/fa/Getting-Started-Create-Solution.md
> +جهت استفاده از ساختار های [React Native](https://reactnative.dev/) در پروژه خود از دستور  `-m react-native` (و یا `--mobile react-native`) استفاده نمایید. این دستور اجازه میدهد تمپلیت اولیه مربوط به
great point

2022-05-22 06:24 UTC, RezaPouya commented
> 

hi , thanks for your response . Im willing to help in translating abp-translate.json. if you are using private repository , just invite me , if you are using public one , then tell me which one it is ...

2022-05-22 10:41 UTC, mheidari988 commented
> > 
> 
> hi , thanks for your response . Im willing to help in translating abp-translate.json. if you are using private repository , just invite me , if you are using public one , then tell me which one it is ...

It's much better if we translate the whole `abp-translate.json` file and then PR. so I started a temporary repo. please check [abp-farsi](https://github.com/mheidari988/abp-farsi) and I invited you and @ashkandehnavi

2023-04-11 11:25 UTC, ebicoglu commented
good work guys! waiting the Persian docs.
thanks

2023-05-15 15:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/abpframework/abp?pullRequest=12160) <br/>All committers have signed the CLA.

2023-06-19 13:30 UTC, hitaspdotnet commented
Good work guys! I am happy to see more Persian joining the framework community soon. Thanks.

2024-07-29 07:14 UTC, hikalkan commented
Hi,
I want to inform you that we've decided to remove all translations of the new documentation system (https://abp.io/docs/latest/)

Because the documentation is frequently changing and none of the translations can catch these changes. Only the Chinese translation was very close to the original documentation, but it was getting our too much effort.

We suggest to you Google Translate or another tool for auto-translation.

We've integrated Google Translate for many languages already:

![image](https://github.com/user-attachments/assets/4b4972dc-aeca-4317-aee7-2fec90abc19a)

Current languages:

![image](https://github.com/user-attachments/assets/cc81d35e-e06d-4922-a565-8aa0df0c89d9)

We will continue to improve that translation system for a smooth reading experience.

2024-07-29 07:14 UTC, closed without merging