Update blazor basic theme docs
abpframework/abp pull request #12537
Opened 2022-05-11 14:32 UTC by enisn

Closes https://github.com/abpframework/abp/issues/8456

2022-05-19 09:03 UTC, hikalkan requested changes

2022-05-19 09:03 UTC, hikalkan commented on docs/en/UI/Blazor/Authentication.md
> +The [application startup template](../../Startup-Templates/Application.md) is properly configured to use OpenId Connect to authenticate the user;
OpenId Connect flow is only used for WASM.

2022-05-19 09:03 UTC, hikalkan commented on docs/en/UI/Blazor/Authentication.md
> +* Finally, they are redirected back to the Blazor application to complete the login process.
Instead of all these, we can write like that:

The Blazor Server application UI is actually a hybrid application that is combined with the MVC UI, and uses the login page provided by the MVC UI. When users enter a page that requires login, they are redirected to the `/Account/Login` page. Once they complete the login process, they are returned back to the application's UI. The login page also contains features like registration, password recovery, etc.

2022-05-19 09:03 UTC, hikalkan commented on docs/en/UI/Blazor/Authentication.md
>  See the [Blazor Security document](https://docs.microsoft.com/en-us/aspnet/core/blazor/security) to understand and customize the authentication process.
This paragraph can also be moved in WASM section.

2022-05-19 09:03 UTC, hikalkan commented on docs/en/UI/Blazor/Basic-Theme.md
> +* Execute `abp-bundle` command under blazor project once.
The command is `abp bundle`, not `abp-bundle`.

2022-05-19 09:03 UTC, hikalkan commented on docs/en/UI/Blazor/Customization-Overriding-Components.md
> +* `@inherits Branding` line inherits the Branding component defined by the [Basic Theme](Basic-Theme.md) (in the `Volo.Abp.AspNetCore.Components.Server.BasicTheme.Themes.Basic` namespace).
I suppose only the namespace is different. You can use inline `{{if}}` for this difference instead of duplicating the whole section.

2022-05-19 09:03 UTC, hikalkan commented on docs/en/UI/Blazor/Theming.md
> +### The Easiest Way
I suppose now we have an ABP CLI command to easily replace the theme with its source code.
See https://docs.abp.io/en/abp/latest/UI/Blazor/Basic-Theme#copy-customize

2022-05-19 09:03 UTC, hikalkan commented on docs/en/UI/Blazor/Theming.md
> +### The Easiest Way
You can also update the same section for MVC and Angular UI.
See for MVC: https://docs.abp.io/en/abp/latest/UI/AspNetCore/Basic-Theme#copy-customize

2022-05-20 08:45 UTC, enisn commented
Done with https://github.com/abpframework/abp/pull/12676

2022-05-20 08:45 UTC, closed without merging