Document how to check global features in MVC UI.
abpframework/abp pull request #12553
Opened 2022-05-13 03:26 UTC by maliming

2022-05-16 05:56 UTC, hikalkan commented
Hi,

Currently, we don't provide any function to check. The developer, herself, works with arrays. At least, we should provide the following API.

`isEnabled` function to check if a feature is enabled or not:

````js
if (abp.globalFeatures.isEnabled(`Ecommerce.Subscription`))
{
  ...
}
````

Also, I didn't understand the purpose of `abp.globalFeatures.moduleEnabledFeatures`. I suppose it is grouping features by modules. But I believe that it is useless. In the UI side, we just need to `abp.globalFeatures.isEnabled` to check if a feature is enabled or not. If `moduleEnabledFeatures` is not used anywhere, we can drop it in JavaScript side, also from the endpoint.

2022-05-17 02:32 UTC, maliming commented
hi

I did the changes.

https://github.com/abpframework/abp/pull/12553/commits/cecc2c1baa53675906bbd96ac27e476783821bad

2022-05-17 07:17 UTC, hikalkan requested changes

2022-05-17 07:17 UTC, hikalkan commented on npm/packs/core/src/abp.js
> +    abp.globalFeatures.enabledFeatures = abp.globalFeatures.enabledFeatures || {};
```suggestion
    abp.globalFeatures.enabledFeatures = abp.globalFeatures.enabledFeatures || [];
```

Shouldn't be like that?

2022-05-17 08:59 UTC, maliming commented on npm/packs/core/src/abp.js
> +    abp.globalFeatures.enabledFeatures = abp.globalFeatures.enabledFeatures || {};
You're right.

2022-05-17 10:32 UTC, hikalkan approved these changes

2022-05-17 10:32 UTC, merged