Add Custom Component Feature to ExtensibleForm.
abpframework/abp pull request #13700
Opened 2022-08-15 14:35 UTC by mahmut-gundogdu

2022-08-22 08:27 UTC, muhammedaltug approved these changes

2022-08-23 04:22 UTC, gizemmutukurt commented
I requested some fixes and changes, you can check it out.

https://github.com/abpframework/abp/issues/13785

2022-08-23 04:23 UTC, gizemmutukurt requested changes
I requested some fixes and changes

2022-08-25 08:39 UTC, muhammedaltug commented on npm/ng-packs/packages/account/src/lib/guards/extensions.guard.ts
> +import {Injectable, Injector} from "@angular/core";
reformat file

2022-08-25 08:39 UTC, muhammedaltug commented on npm/ng-packs/packages/core/src/lib/validators/username.validator.ts
> +import {AbstractControl, ValidatorFn} from '@angular/forms';
reformat file

2022-08-25 08:39 UTC, muhammedaltug commented on npm/ng-packs/packages/theme-shared/extensions/src/lib/components/extensible-form/extensible-form-prop.component.ts
> +import {NgbDateAdapter, NgbTimeAdapter} from '@ng-bootstrap/ng-bootstrap';
reformat file

2022-08-25 08:39 UTC, muhammedaltug commented on npm/ng-packs/packages/theme-shared/extensions/src/lib/components/extensible-form/extensible-form.component.ts
> +import {ControlContainer, FormGroup, FormGroupDirective} from '@angular/forms';
reformat file

2022-08-25 08:39 UTC, muhammedaltug commented on npm/ng-packs/packages/theme-shared/extensions/src/lib/models/form-props.ts
> +  readonly template? : Type<any>
reformat file

2022-08-25 08:39 UTC, muhammedaltug commented on npm/ng-packs/packages/theme-shared/extensions/src/lib/models/props.ts
> +    public readonly template? : Type<any>,
reformat file

2022-08-25 08:39 UTC, muhammedaltug commented on npm/ng-packs/packages/theme-shared/extensions/src/lib/tokens/extensions.token.ts
> + import {FormProp} from "../models/form-props";
reformat file

2022-08-29 05:41 UTC, gizemmutukurt approved these changes

2022-08-29 05:42 UTC, merged