Docs module improvements discussion
abpframework/abp pull request #13804
Opened 2022-08-24 10:40 UTC by salihozkara

Resolves #13585 

![image](https://user-images.githubusercontent.com/58659931/186397851-f707c1f9-36f1-4235-a67e-05b8949047d0.png)
![image](https://user-images.githubusercontent.com/58659931/186397897-7ad4ff21-f2fa-4834-b46b-f1709ceede23.png)
![image](https://user-images.githubusercontent.com/58659931/186397980-3be0a711-0faf-415b-8c1e-efd07d50c20e.png)
![image](https://user-images.githubusercontent.com/58659931/186398027-c7d536ce-e956-45a5-8d11-1fb2ee2594f8.png)
![image](https://user-images.githubusercontent.com/58659931/186398073-349fae1a-b4d3-46fa-870f-7f5bb1e4a0e3.png)
![image](https://user-images.githubusercontent.com/58659931/186398171-532ac79b-029b-4646-bb06-6a6d26ff1556.png)
![image](https://user-images.githubusercontent.com/58659931/186398242-3e0da4c1-6a4d-480a-8b95-e1de3e241cc6.png)
![image](https://user-images.githubusercontent.com/58659931/186398312-c1726784-eb56-4c17-9497-d386195a9130.png)
![image](https://user-images.githubusercontent.com/58659931/186398377-9d6aad8e-a9ad-43cb-9171-178fd2db9b8d.png)

2022-08-25 09:03 UTC, ebicoglu commented
when you finish testing, could you notify me @gizemmutukurt

2022-08-29 05:33 UTC, gizemmutukurt commented
I am displaying error in filtering

![632678c3-f1b5-4e3e-a9da-d1d58ff4da2b](https://user-images.githubusercontent.com/99716457/187129770-1fb8243d-47e5-4701-8ba2-936368c2a463.gif)

2022-08-29 05:34 UTC, gizemmutukurt requested changes
Error in filter needs to be fixed

2022-08-29 13:04 UTC, gizemmutukurt approved these changes

2022-08-29 16:43 UTC, ebicoglu approved these changes

2022-08-29 16:43 UTC, merged