hu translation
abpframework/abp pull request #13911
Opened 2022-09-02 10:11 UTC by lszabados

I updated the Hungarian translation.

2022-09-05 06:29 UTC, berkansasmaz commented
Thanks, @lszabados 🎉

I will review as soon as possible.

2022-09-09 08:02 UTC, berkansasmaz requested changes
Thank you again for your huge contribution. I have requested a few changes. Any chance of fixing these?

2022-09-09 08:02 UTC, berkansasmaz commented on abp_io/AbpIoLocalization/AbpIoLocalization/Commercial/Localization/Resources/hu.json
> +    "DowngradeLicensePlanExplanation": "Nem módosíthatja a meglévő licenszcsomagot. De vásárolhat egy új alacsonyabb licenszcsomagot, és folytathatja a fejlesztést az új licenszen. Miután megvásárolt
Any chance to change `abp login<username> -o<organization>` to `abp login <username> -o <organization>`?

2022-09-09 08:02 UTC, berkansasmaz commented on abp_io/AbpIoLocalization/AbpIoLocalization/Commercial/Localization/Resources/hu.json
> +    "MyOrganizations_Detail_YourPrivateNugetSource": "Az Ön privát NuGet-forrása <a href=\"{0}\" arget=\"_blank\" class=\"text-primary\" rel=\"noopener\">{0}</a>",
Any chance to change `arget=\"_blank\"` to `target=\"_blank\"`?

You can also make this change for other languages. For instance: https://github.com/abpframework/abp/blob/a58f8d77da2c2bcbb3ed3035cdb584f82924ed0c/abp_io/AbpIoLocalization/AbpIoLocalization/Commercial/Localization/Resources/en.json#L551

2022-09-09 08:02 UTC, berkansasmaz commented on abp_io/AbpIoLocalization/AbpIoLocalization/Commercial/Localization/Resources/hu.json
> +    "WatchCrudPagesVideo": "Nézze meg a &quot;CRUD oldalak létrehozása az ABP Suite segítségével&quot; videót!",
We try to avoid HTML entities wherever possible so can you use `"` instead of `&quot;`?

See: https://github.com/abpframework/abp/blob/a58f8d77da2c2bcbb3ed3035cdb584f82924ed0c/abp_io/AbpIoLocalization/AbpIoLocalization/Commercial/Localization/Resources/en.json#L732


You can also make this fix for other files(e.g. `modules/cms-kit/src/Volo.CmsKit.Domain.Shared/Volo/CmsKit/Localization/Resources/hu.json`) in this PR.

Note: Don't forget the escape character :)

2022-09-09 08:02 UTC, berkansasmaz commented on modules/cms-kit/src/Volo.CmsKit.Domain.Shared/Volo/CmsKit/Localization/Resources/hu.json
> +    "PageSlugInformation": "A Slug az url-en használatos. Az Ön URL-je a következő lesz: „/pages/{{slug}}”.",
As far as I know `pages/{{slug}}` used to be used.

Current version:

https://github.com/abpframework/abp/blob/2745ee6c4fdc59aa3fd6644a9a8bf73245e76d90/modules/cms-kit/src/Volo.CmsKit.Domain.Shared/Volo/CmsKit/Localization/Resources/en.json#L78

2022-09-11 10:42 UTC, lszabados commented on abp_io/AbpIoLocalization/AbpIoLocalization/Commercial/Localization/Resources/hu.json
> +    "DowngradeLicensePlanExplanation": "Nem módosíthatja a meglévő licenszcsomagot. De vásárolhat egy új alacsonyabb licenszcsomagot, és folytathatja a fejlesztést az új licenszen. Miután megvásárolt
Ready

2022-09-11 10:42 UTC, lszabados commented on abp_io/AbpIoLocalization/AbpIoLocalization/Commercial/Localization/Resources/hu.json
> +    "MyOrganizations_Detail_YourPrivateNugetSource": "Az Ön privát NuGet-forrása <a href=\"{0}\" arget=\"_blank\" class=\"text-primary\" rel=\"noopener\">{0}</a>",
Ready

2022-09-11 10:43 UTC, lszabados commented on abp_io/AbpIoLocalization/AbpIoLocalization/Commercial/Localization/Resources/hu.json
> +    "WatchCrudPagesVideo": "Nézze meg a &quot;CRUD oldalak létrehozása az ABP Suite segítségével&quot; videót!",
Fixed here and many other places

2022-09-11 10:44 UTC, lszabados commented on modules/cms-kit/src/Volo.CmsKit.Domain.Shared/Volo/CmsKit/Localization/Resources/hu.json
> +    "PageSlugInformation": "A Slug az url-en használatos. Az Ön URL-je a következő lesz: „/pages/{{slug}}”.",
Ready

2022-09-11 10:45 UTC, lszabados commented
Thanks for the comments, I tried to fix everything.

2022-09-12 06:42 UTC, berkansasmaz approved these changes
LGTM 🎉

2022-09-12 06:42 UTC, merged