[DRAFT] Add customization  docs for Leptonx  lite
abpframework/abp pull request #14225
Opened 2022-10-04 12:22 UTC by mahmut-gundogdu

resolves #444

2022-10-07 12:19 UTC, ismcagdas requested changes
We can also remove "Page Alerts Component" section if that part is not replacable.

2022-10-07 12:19 UTC, ismcagdas commented on docs/en/Themes/LeptonXLite/Angular.md
> +The main responsibility of a theme iss to **provides** the layouts. There are **three pre-defined layouts that must be implemented by all the themes:**
```suggestion
The main responsibility of a theme is to **provide** the layouts. There are **three pre-defined layouts that must be implemented by all the themes:**
```

2022-10-07 12:20 UTC, ismcagdas commented
@braim23 could you also check this PR when you have time.

2022-10-07 12:21 UTC, braim23 commented
> @braim23 could you also check this PR when you have time.

I'll do that once I'm done with the issue I'm working on

2022-10-10 05:50 UTC, braim23 approved these changes

2022-10-10 05:54 UTC, ismcagdas approved these changes

2022-10-10 05:55 UTC, merged