Update Data-Seeding.md
abpframework/abp pull request #14334
Opened 2022-10-16 01:58 UTC by maliming

Resolve #14316

2022-10-20 08:30 UTC, braim23 approved these changes

2022-11-02 15:10 UTC, hikalkan requested changes

2022-11-02 15:10 UTC, hikalkan commented on docs/en/Data-Seeding.md
> +### Separate Units Of Work
```suggestion
### Separate Unit Of Works
```

2022-11-02 15:10 UTC, hikalkan commented on docs/en/Data-Seeding.md
> +We provide an extension method of `SeedInSeparateUowAsync` to create a separate unit of work for each `IDataSeedContributor`.
```suggestion
We provide an extension method of `SeedInSeparateUowAsync` for the `IDataSeeder` service to create a separate unit of work for each `IDataSeedContributor`.
```

2022-11-03 07:19 UTC, hikalkan approved these changes

2022-11-03 07:19 UTC, merged