Revision for CMS Kit Features naming
abpframework/abp pull request #14755
Opened 2022-11-21 11:20 UTC by malikmasis

fixes https://github.com/abpframework/abp/issues/14733

2022-11-21 11:22 UTC, malikmasis commented
![image](https://user-images.githubusercontent.com/13196534/203038201-e2ee64a6-95b7-4676-9817-4d69b1bdc20e.png)

2022-11-22 07:39 UTC, enisn requested changes

2022-11-22 07:39 UTC, enisn commented on modules/cms-kit/src/Volo.CmsKit.Domain.Shared/Volo/CmsKit/Localization/Resources/en.json
> +    "Feature:GlobalResourceEnableDescription": "CMS Kit's dynamic globa resoruce system",
```suggestion
    "Feature:GlobalResourceEnableDescription": "CMS Kit's global resoruces feature that allows managing global styles & scripts.",
```

2022-11-22 07:39 UTC, enisn commented on modules/cms-kit/src/Volo.CmsKit.Domain.Shared/Volo/CmsKit/Localization/Resources/en.json
> +    "Feature:CommentEnableDescription": "CMS Kit's comment system",
```suggestion
    "Feature:CommentEnableDescription": "CMS Kit's comment system allows commenting on entities such as BlogPost.",
```

2022-11-22 07:39 UTC, enisn commented on modules/cms-kit/src/Volo.CmsKit.Domain.Shared/Volo/CmsKit/Localization/Resources/en.json
> +    "Feature:MenuEnableDescription": "CMS Kit's dynamic menu system",
```suggestion
    "Feature:MenuEnableDescription": "CMS Kit's dynamic menu system that allows adding/removing application menus dynamically.",
```

2022-11-22 07:39 UTC, enisn commented on modules/cms-kit/src/Volo.CmsKit.Domain.Shared/Volo/CmsKit/Localization/Resources/en.json
> +    "Feature:PageEnableDescription": "CMS Kit's page system",
```suggestion
    "Feature:PageEnableDescription": "CMS Kit's page system that allows creating static pages with specific URL.",
```

2022-11-22 07:39 UTC, enisn commented on modules/cms-kit/src/Volo.CmsKit.Domain.Shared/Volo/CmsKit/Localization/Resources/en.json
> +    "Feature:RatingEnableDescription": "CMS Kit's rating system",
```suggestion
    "Feature:RatingEnableDescription": "CMS Kit's rating system that allows users to rate entities such as BlogPost.",
```

2022-11-22 07:39 UTC, enisn commented on modules/cms-kit/src/Volo.CmsKit.Domain.Shared/Volo/CmsKit/Localization/Resources/en.json
> +    "Feature:ReactionEnableDescription": "CMS Kit's reaction system",
```suggestion
    "Feature:ReactionEnableDescription": "CMS Kit's reaction system that allows users to send reactions to entities such as BlogPost, Comments, etc.",
```

2022-11-22 07:39 UTC, enisn commented on modules/cms-kit/src/Volo.CmsKit.Domain.Shared/Volo/CmsKit/Localization/Resources/en.json
> +    "Feature:TagEnableDescription": "CMS Kit's tag system"
```suggestion
    "Feature:TagEnableDescription": "CMS Kit's tag system that allows tagging entities such as BlogPost."
```

2022-11-22 07:39 UTC, enisn commented on modules/cms-kit/src/Volo.CmsKit.Domain.Shared/Volo/CmsKit/Localization/Resources/en.json
> +    "Feature:BlogEnableDescription": "CMS Kit's blogpost system",
```suggestion
    "Feature:BlogEnableDescription": "CMS Kit's blogpost system that allows create blogs and posts dynamically in the application.",
```

2022-11-22 10:18 UTC, enisn approved these changes

2022-11-22 11:12 UTC, merged