CMS-KIT: add link types to links in comments as optional
abpframework/abp pull request #15489
Opened 2023-01-23 10:51 UTC by salihozkara

Resolves #15458

2023-01-23 15:01 UTC, EngincanV requested changes

2023-01-23 15:01 UTC, EngincanV commented on modules/cms-kit/src/Volo.CmsKit.Public.Web/Pages/CmsKit/Shared/Components/Commenting/CommentingViewComponent.cs
> +        var referralLinks = viewModel.ReferralLinks?.ToArray();
No need to convert the `IEnumerable<string>` to an array. 

```suggestion
        var referralLinks = viewModel.ReferralLinks.JoinAsString(" ");
```

2023-01-23 15:01 UTC, EngincanV commented on modules/cms-kit/src/Volo.CmsKit.Public.Web/Pages/CmsKit/Shared/Components/Commenting/CommentingViewComponent.cs
> +            comment.Text = await MarkdownToHtmlRenderer.RenderAsync(comment.Text, allowHtmlTags: false, preventXSS: true, referralLinks: referralLinks.JoinAsString(" "));
See my comment above, if you do it as I suggested, you can just write `referralLinks` here.

2023-01-23 15:01 UTC, EngincanV commented on modules/cms-kit/src/Volo.CmsKit.Common.Web/Renderers/MarkdownToHtmlRenderer.cs
> +        if(referralLinks != null)
Check for both null and whitespace situations:

```suggestion
        if(!string.IsNullOrWhiteSpace(referralLinks)
```

2023-01-23 15:40 UTC, EngincanV approved these changes

2023-01-24 06:50 UTC, berkansasmaz approved these changes

2023-01-24 07:37 UTC, merged