Feat card component
abpframework/abp pull request #15584
Opened 2023-02-02 13:45 UTC by bariscanyilmaz

### Description

Resolves #5237 

Created new card component to use instead of card class  

### Checklist

- [ ] I fully tested it as developer / designer and created unit / integration tests
- [ ] I documented it (or no need to document or I will create a separate documentation issue)

2023-02-02 13:49 UTC, mahmut-gundogdu requested changes

2023-02-02 13:49 UTC, mahmut-gundogdu commented on npm/ng-packs/packages/theme-shared/src/lib/components/card/card.component.ts
> +  <div class="card-title" *ngIf="cardTitleTemplate">
card-title component should constain 
` <div class="card-title" *ngIf="cardTitleTemplate">
    <ng-content select="abp-card-title"></ng-content>
  </div>`
  that  or it should be removed.

2023-02-02 13:49 UTC, mahmut-gundogdu commented on npm/ng-packs/packages/theme-shared/src/lib/components/card/card.component.ts
> +  <div class="card-body" *ngIf="cardBodyTemplate">
same for card-body

2023-02-02 13:49 UTC, mahmut-gundogdu commented on npm/ng-packs/packages/theme-shared/src/lib/components/card/card.component.ts
> +  @ContentChild(CardBodyComponent)
maybe use ng-content not component.

2023-02-02 13:49 UTC, mahmut-gundogdu commented on npm/ng-packs/packages/theme-shared/src/lib/theme-shared.module.ts
> +  CardBodyComponent,
I would do card.module.ts or card.standalone

2023-02-02 13:52 UTC, muhammedaltug commented on npm/ng-packs/packages/theme-shared/src/lib/components/card/card.component.ts
> +  @Input() class:string
please change input name to 'cardClass'. Do not use native HTML attributes as input

2023-02-02 13:52 UTC, muhammedaltug commented on npm/ng-packs/packages/theme-shared/src/lib/components/card/card.component.ts
> +  @Input() style:string
please change input name to 'cardStyle'. Do not use native HTML attributes as input

2023-02-15 08:50 UTC, muhammedaltug approved these changes

2023-02-16 10:01 UTC, mahmut-gundogdu approved these changes

2023-02-16 10:01 UTC, merged