Card component document
abpframework/abp pull request #15755
Opened 2023-02-20 10:50 UTC by bariscanyilmaz

### Description

Create card component document.

### Checklist

- [x] I fully tested it as developer / designer and created unit / integration tests
- [x] I documented it (or no need to document or I will create a separate documentation issue)

2023-02-20 15:15 UTC, braim23 approved these changes

2023-02-21 00:10 UTC, rqx110 commented on docs/en/UI/Angular/Card-Component.md
> +    SharedModule,
```suggestion
    ThemeSharedModule ,
```

2023-02-22 06:57 UTC, hikalkan requested changes

2023-02-22 06:57 UTC, hikalkan commented on docs/en/UI/Angular/Card-Component.md
> +ABP Card Component is a built-in `ThemeSharedModule` component. If you've imported a shared module into your feature module, you don't need to do anything.
```suggestion
ABP Card Component is a part of the `ThemeSharedModule` module. If you've imported that module into your module, you don't need to import it again. If not, first import it uas shown below:
```

2023-02-22 06:57 UTC, hikalkan commented on docs/en/UI/Angular/Card-Component.md
> +        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla commodo condimentum ligula, sed varius nibh eleifend sit amet. Maecenas facilisis vel arcu nec maximus.</abp-card-body>
```suggestion
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla commodo condimentum ligula, sed varius nibh eleifend sit amet. Maecenas facilisis vel arcu nec maximus.
      </abp-card-body>
```

2023-02-22 06:59 UTC, hikalkan commented
We show usages of the `abp-card`, `abp-card-body` and `abp-card-title` elements. Isn't there more? If so, we should write a list of all defined elements and all of their options.

2023-02-22 20:18 UTC, bariscanyilmaz commented
> We show usages of the `abp-card`, `abp-card-body` and `abp-card-title` elements. Isn't there more? If so, we should write a list of all defined elements and all of their options.

We haven't implemented all elements yet. As new elements are added, document will be updated.

2023-02-24 15:13 UTC, mahmut-gundogdu approved these changes

2023-03-02 06:48 UTC, hikalkan approved these changes

2023-03-02 06:48 UTC, merged