Mvc : abpdatepicker and abpdaterangepicker add
abpframework/abp pull request #15806
Opened 2023-02-25 12:52 UTC by salihozkara

We added two new tags, abpdatepicker and abpdaterangepicker, that utilize the daterangepicker package for MVC. These tags aim to facilitate datepicker events and make date selection easier for users. 

![image](https://user-images.githubusercontent.com/58659931/221357680-8a0d6e97-bb4c-4fda-aed5-63d7c0675612.png)
![image](https://user-images.githubusercontent.com/58659931/221357687-019cb10d-ee11-4be5-8935-eec1156dfc7e.png)
![image](https://user-images.githubusercontent.com/58659931/221357707-104b3a4a-36e3-41d7-9be1-5dd2560590c7.png)
![image](https://user-images.githubusercontent.com/58659931/221357717-ba69dbfb-993f-4fb9-95c7-bc9648d13348.png)

2023-03-02 06:25 UTC, ebicoglu commented
we'll make a code-review session for this PR

2023-03-09 13:41 UTC, ebicoglu requested changes

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +- `[DatePickerOptions()]`: Sets the options of datepicker. You can use a localization key directly. See [datepicker options](https://www.daterangepicker.com/#options) for more information.)
information.)

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +You can set some of the attributes on your c# property, or directly on html tag. If you are going to use this property in a [abp-dynamic-form](Dynamic-forms.md), then you can only set these propertie
HTML

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `[InputInfoText()]`: Sets a small info text for input. You can use a localization key directly.
Sets the description are of the input

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `[DisabledInput]` :  Input is disabled.
Sets the input as disabled.

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `[ReadOnlyInput]`: Input is read-only.
Sets the input as read-only.

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +- `[DatePickerOptions()]`: Sets the options of datepicker. You can use a localization key directly. See [datepicker options](https://www.daterangepicker.com/#options) for more information.)
Sets the predefined options of the date picker. See the available [datepicker options](https://www.daterangepicker.com/#options).

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +`[DatePicker]` : Date picker is enabled.
Sets the input as datepicker. Especially for string properties.

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +`[DateRangePicker()]` : Sets the picker id for date range picker. This is used to link start and end date pickers. And sets this property is start date or end date.
Sets the picker id for the date range picker. You can set the property as a start date by setting `IsStart=true`  or leave it as default/false to set it as an end date.

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `info`: Sets a small info text for input. You can use a localization key directly.
Sets text for the input. You can directly use a localization key.

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `auto-focus`: If true, browser auto focuses on the element.
It lets the browser set focus to the element when its value is true.

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `size`: Sets size of form-control wrapper element. Available values are
Sets the size of the form-control wrapper element.

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `disabled`: Input is disabled.
Sets the input as disabled.

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `readonly`: Input is read-only.
Sets the input as read-only.

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `label`: Sets the label for input.
Sets the label of input.

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `display-required-symbol`: Adds the required symbol (*) to label if input is required. Default `True`.
Adds the required symbol `(*)` to the label when the input is required. The default value is `True`.

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `open-button`: If true, a button will be added to open datepicker. Default `True`.
A button to open the datepicker will be added when its `True`. The default value is `True`.

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `clear-button`: If true, a button will be added to clear datepicker. Default `True`.
---

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `is-utc`: If true, datepicker will use UTC date. Default `False`.
---

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `is-iso`: If true, datepicker will use ISO date. Default `False`.
---

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `date-format`: Sets the date format. Default your culture's date format. (JS format)
Sets the date format of the input. The default format is the user's culture date format. You need to provide a JavaScript date format convention. Eg:  `YYYY-MM-DDTHH:MM:SSZ`

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* `date-separator`: Sets the range date separator. Default `-`.
Sets a character to separate start and end dates. The default value is `-`

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +* Other attributes will be added to the input element and [datepicker options](https://www.daterangepicker.com/#options).
* Other non-mapped attributes will be automatically added to the input element as is. See the available [datepicker options](https://www.daterangepicker.com/#options).

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +You can set label of your input in different ways:
You can set the label of the input in several ways:

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +- You can use `Label` attribute and directly set the label. But it doesn't auto localize your localization key. So use it as `label="@L["{LocalizationKey}"].Value"`.
You can use the `Label` attribute to set the label directly. This property does not automatically localize the text. To localize the label, use `label="@L["{LocalizationKey}"].Value"`.

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +- You can set it using `[Display(name="{LocalizationKey}")]` attribute of Asp.Net Core.
ASP.NET

2023-03-09 13:41 UTC, ebicoglu commented on docs/en/UI/AspNetCore/Tag-Helpers/Form-elements.md
> +- You can just let **abp** find the localization key for the property. It will try to find "DisplayName:{PropertyName}" or "{PropertyName}" localization keys, if `label` or `[DisplayName]` attributes
If the `label` or `[DisplayName]` attributes are not set, it tries to find the localization by convention. For example `DisplayName:{YourPropertyName}` or `{YourPropertyName}`. If your property name is FullName, it will search for `DisplayName:FullName` or `{FullName}`.

2023-03-09 13:41 UTC, ebicoglu commented on framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bootstrap/TagHelpers/Form/DatePicker/IAbpDatePickerOptions.cs
> +public interface IAbpDatePickerOptions
Copy paste the descriptions from https://www.daterangepicker.com/#options

2023-03-09 14:11 UTC, ebicoglu commented
@hikalkan you may want to review this PR

2023-03-10 14:39 UTC, hikalkan commented
I think we can add some more example usages in the documentation (including one with `abp-dynamic-form`).

2023-03-21 09:20 UTC, ebicoglu commented on framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/dom-event-handlers.js
> +            $container[0].datePicker = $datePicker[0];
if there's no datepicker in the result list.

2023-03-22 06:37 UTC, ebicoglu approved these changes

2023-03-24 21:34 UTC, gizemmutukurt commented
- [ ] An error is received when adding the info option.
![image](https://user-images.githubusercontent.com/99716457/227644786-4aa1b4e5-5f5e-408b-92d0-e6808a24eaa9.png)

- [ ] The disable option works within the field, but does not prevent selection from the marked field.
![image](https://user-images.githubusercontent.com/99716457/227529293-983b095f-9258-4930-a77e-f361a404be2a.png)

- [ ] The readonly option does not work correctly.
![68b9dfe1-e539-495f-b1b0-3a7578cb55bb](https://user-images.githubusercontent.com/99716457/227531109-63975e09-1ba8-4891-9d2e-d0ff6ac383b7.gif)

- [ ] single-and-clear-button option not available in document
![image](https://user-images.githubusercontent.com/99716457/227532463-4624cdc1-d9ba-4f31-beb5-6e5b4ea1a53f.png)

2023-03-27 21:33 UTC, gizemmutukurt requested changes
Problems added in the comment should be fixed

2023-03-30 10:59 UTC, gizemmutukurt approved these changes

2023-03-30 12:50 UTC, yekalkan approved these changes

2023-03-30 12:50 UTC, merged

2023-05-31 04:01 UTC, weiwxg commented
@salihozkara how to set empty default value to daterangepicker?

2023-05-31 09:38 UTC, salihozkara commented
@weiwxg https://github.com/abpframework/abp/pull/16651 could your problem be related to this

2023-05-31 09:57 UTC, weiwxg commented
> @weiwxg #16651 could your problem be related to this

I‘ve resolved it. but still appreciate your reply