Update AbpStringExtensions.ReplaceFirst, to spans
abpframework/abp pull request #15878
Opened 2023-03-04 13:55 UTC by merijng

### Description

Resolves #15877

you can see the benchmark in the issue (#15877).

### Checklist

- [ ] I fully tested it as developer / designer and created unit / integration tests
- [ ] I documented it (or no need to document or I will create a separate documentation issue)

### How to test it?

- To test the performance, use [my seperate repo](https://github.com/merijng/ConsoleBenchmarkDotNet). 
- Output and input strings remain the same, you can test that using the original unit tests (that still work).

2023-03-04 20:04 UTC, berkansasmaz commented
Thanks, @merijng 🎉 

I will review your PR as soon as possible.

2023-03-06 13:51 UTC, berkansasmaz requested changes
I've reviewed your code and the performance improvement is really great, but there are a few problems. The `ReplaceFirst` method is defined in the framework, so no assumptions can be made, for example, the `ReplaceFirst` method can be called on a string with 5 characters or it can be called on a string with 50,000 characters. Since we cannot make such assumptions, we must be careful when using `stackalloc` otherwise a stack overflow exception may be encountered.

For example, a sentence in dotnet's documentation:
> Because the amount of memory available on the stack depends on the environment in which the code is executed, be conservative when you define the actual limit value.

_ref: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/stackalloc_

You can also check an article on the subject: https://vcsjones.dev/stackalloc/

If you want to perform repetitive tests, you can test the problem with the following data.

```charp
"Test".PadLeft(5000000, 't').ReplaceSpan("t".PadLeft(100000, 't').PadLeft(100000, 'e').PadLeft(300000, 't'), "XX", StringComparison.OrdinalIgnoreCase);
```

By the way, thank you very much for the test project you sent. 

---

Here, this problem can be solved by two methods:
1. As mentioned [in this document](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/stackalloc), with code similar to the following:

```charp
int length = 1000;
Span<byte> buffer = length <= 1024 ? stackalloc byte[length] : new byte[length];
```

2. By blending the old method with the new method:

```charp
int length = 1000;
if (length > 1024){
    ReplaceSubstring()
} else {
     ReplaceSpan()
}
```

When I look at the benchmark results in both methods, they are almost the same, so the first method seems more appropriate to me, so as not to overcomplicate the code.

But I need another pair of eyes to make sure I don't miss anything. @maliming, can you review this PR after the relevant changes?

2023-03-06 18:37 UTC, merijng commented
@berkansasmaz @maliming 

Just changed the commit, to the first option. I agree!

**By the way:**
Why is ABP on netstandard2.0? In netstandard2.1 (/net7), you can use string.Concat which is even faster. Below an example+benchmark (you can add it to the console). The other substring methods in AbpStringExtensions might also benefit from an upgrade to netstandard 2.1.

```
public static string ReplaceSpan2(this string str, string search, string replace, StringComparison comparisonType = StringComparison.Ordinal)
        {
            //Check.NotNull(str, nameof(str));
            int pos = str.IndexOf(search, comparisonType);
            if (pos < 0)
            {
                return str;
            }

            var sourceSpan = str.AsSpan();
            return string.Concat(sourceSpan.Slice(0, pos), replace, sourceSpan.Slice(pos + search.Length));
        }
```

![image](https://user-images.githubusercontent.com/6886678/223199817-143ece70-f0a9-40a5-b3f0-94985c6dc5a2.png)

2023-03-07 01:25 UTC, maliming commented
hi

> Why is ABP on netstandard2.0? In netstandard2.1 (/net7)

https://github.com/abpframework/abp/issues/5676#issuecomment-706354605

2023-03-07 16:35 UTC, merijng commented
@maliming 

First, the change as requested has been done.

Second, what I mean with my question is:

If you have planned netstandard2.1 in the near future, then spans can upgrade the performance of ABP in more ways (like shown in my previous post). Beside that: in netstandard2.1 code of spans is way cleaner.

If not: then I guess this is the only pull request whereas spans can upgrade ABP :(

**About compatibility with .NET Standard 2.1**
I see no reason to support .NET Framework and older versions of .NET, in ABP 7+?

Reference: 

- [Announcing .NET Standard 2.1](https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/)
- [Compatiblity](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1)

2023-03-09 07:09 UTC, maliming commented
hi

We can discuss `.NET Standard` version in a new issue.

2023-03-09 07:14 UTC, maliming approved these changes

2023-03-09 07:17 UTC, maliming approved these changes

2023-03-09 07:32 UTC, berkansasmaz approved these changes

2023-03-09 08:03 UTC, merged