tasks done #15935
abpframework/abp pull request #15938
Opened 2023-03-10 15:57 UTC by masumulu28

Resolves #15884, resolves #15935

2023-03-27 08:28 UTC, mahmut-gundogdu requested changes

2023-03-27 08:28 UTC, mahmut-gundogdu commented on npm/ng-packs/packages/core/src/lib/core.module.ts
> +        {
I think the group might be optional. Depend on the behavior.  If I didn't add any group, menu behavior shouldn't change. isn't it?

2023-03-27 08:28 UTC, mahmut-gundogdu commented on npm/ng-packs/packages/core/src/lib/models/common.ts
> +    group?: Group<any>;
Why we set any as group key type ? there is already a default value.

2023-03-27 08:28 UTC, mahmut-gundogdu commented on docs/en/UI/Angular/Modifying-the-Menu.md
> +  visible: RouteGroup<ABP.Route>[] | undefined = this.routes.groupedVisible;
I didn't see code where the using visible fn or observe

2023-03-27 09:09 UTC, masumulu28 commented on npm/ng-packs/packages/core/src/lib/models/common.ts
> +    group?: Group<any>;
Thi is old version of code, this is the [new version](https://github.com/abpframework/abp/blob/e21e8686fce1a05f77b135d2e0bd95c96faac096/npm/ng-packs/packages/core/src/lib/models/common.ts#L74)

2023-03-27 09:25 UTC, masumulu28 commented on npm/ng-packs/packages/core/src/lib/core.module.ts
> +        {
It won't effect to default menu behavior, only using in groupedTree & groupedTree$ getter methods. This methods will return undefined when there is no any group in tree, [control line](https://github.com/abpframework/abp/blob/e21e8686fce1a05f77b135d2e0bd95c96faac096/npm/ng-packs/packages/core/src/lib/utils/tree-utils.ts#L81)

2023-03-28 12:23 UTC, mahmut-gundogdu approved these changes

2023-03-28 16:07 UTC, braim23 approved these changes

2023-03-30 21:20 UTC, merged