page-alert-container component updated for HTML content
abpframework/abp pull request #16049
Opened 2023-03-22 08:57 UTC by masumulu28

resolves #16026

2023-03-22 11:58 UTC, mahmut-gundogdu requested changes

2023-03-22 11:58 UTC, mahmut-gundogdu commented on npm/ng-packs/packages/theme-basic/src/lib/components/page-alert-container/page-alert-container.component.html
> +      [innerHTML]="alert.title | abpLocalization: alert.titleLocalizationParams"
Can you search/check innerHtml might be XSS issue. We should sanitize the content of html.

2023-03-22 11:59 UTC, masum-ulu commented on npm/ng-packs/packages/theme-basic/src/lib/components/page-alert-container/page-alert-container.component.html
> +      [innerHTML]="alert.title | abpLocalization: alert.titleLocalizationParams"
Okay, you right I'll modify solution

2023-03-22 12:02 UTC, mahmut-gundogdu commented on npm/ng-packs/packages/theme-basic/src/lib/components/page-alert-container/page-alert-container.component.html
> +      [innerHTML]="alert.title | abpLocalization: alert.titleLocalizationParams"
Please if apply any changes, reflect changes lepton-x side too.

2023-03-27 13:07 UTC, mahmut-gundogdu approved these changes

2023-03-28 10:15 UTC, merged