Documantation and test created for `abpSafeHtml` & `page-alert`
abpframework/abp pull request #16117
Opened 2023-03-28 22:23 UTC by masumulu28

Resolves #16097

- [x] I fully tested it as developer / designer and created unit / integration tests
- [x] I documented it (or no need to document or I will create a separate documentation issue)

## Document

![image](https://user-images.githubusercontent.com/49063256/228379701-fe5d20b5-76f3-4e1a-aa6e-36038661e63c.png)

2023-03-29 11:13 UTC, mahmut-gundogdu requested changes

2023-03-29 11:13 UTC, mahmut-gundogdu commented on npm/ng-packs/packages/core/src/lib/tests/safe-html.pipe.spec.ts
> +    const inputs = [42, false, {}, []];
You may turn to  test.each like `date-time.adapter.spec.ts`

2023-03-30 10:13 UTC, braim23 approved these changes

2023-03-30 11:16 UTC, mahmut-gundogdu approved these changes

2023-03-30 11:16 UTC, merged