remove clientSecret from login url
abpframework/abp pull request #16468
Opened 2023-05-02 13:28 UTC by bariscanyilmaz

### Description

Resolves #16302 

TODO: Removes client_secret from login url in react native AccountAPI

### Checklist

- [x] I fully tested it as developer / designer and created unit / integration tests
- [x] I documented it (or no need to document or I will create a separate documentation issue)

2023-05-02 13:33 UTC, mahmut-gundogdu requested changes
it should be conditional. user might be use openid or identity server.

2023-05-03 00:43 UTC, maliming commented on templates/app/react-native/src/api/AccountAPI.js
> -    data: `grant_type=password&scope=${oAuthConfig.scope}&username=${username}&password=${password}&client_id=${oAuthConfig.clientId}&client_secret=${oAuthConfig.clientSecret}`,
We can consider checking the `clientSecret` of `oAuthConfig`.
Add it by `if (oAuthConfig.clientSecret)`

2023-05-03 08:24 UTC, maliming approved these changes

2023-05-03 08:29 UTC, masumulu28 approved these changes

2023-05-03 10:11 UTC, mahmut-gundogdu requested changes
it must be sent directly. no need to serilize to string

2023-05-04 01:11 UTC, maliming approved these changes

2023-05-05 13:35 UTC, masumulu28 approved these changes

2023-05-10 13:14 UTC, mahmut-gundogdu approved these changes

2023-05-10 13:14 UTC, mahmut-gundogdu approved these changes

2023-05-10 13:14 UTC, mahmut-gundogdu approved these changes

2023-05-10 13:14 UTC, merged