Cms-Kit - comment enhancement on admin side
abpframework/abp pull request #16476
Opened 2023-05-03 11:12 UTC by onurpicakci

Resolves #16458 

<img width="1133" alt="Ekran Resmi 2023-05-03 14 10 24" src="https://user-images.githubusercontent.com/98148844/235900323-f1476743-79ef-4bfd-9484-2874962003ae.png">

- [x] I fully tested it as developer / designer and created unit / integration tests
- [x] I documented it (or no need to document or I will create a separate documentation issue)

2023-05-04 06:12 UTC, EngincanV requested changes

2023-05-04 06:12 UTC, EngincanV commented on modules/cms-kit/src/Volo.CmsKit.Admin.Web/Pages/CmsKit/Comments/index.js
> +                    console.log(data);
Delete `console.log`.

2023-05-04 06:12 UTC, EngincanV commented on modules/cms-kit/src/Volo.CmsKit.Domain/Volo/CmsKit/Comments/Comment.cs
> +    public virtual string CommentUrl { get; set; }
It should be `Url`. (*CommentUrl* is meaningless, because we define the property in the Comment entity)

2023-05-04 06:12 UTC, EngincanV commented on modules/cms-kit/src/Volo.CmsKit.Public.Application.Contracts/Volo/CmsKit/Public/Comments/CommentDto.cs
> +    public string CommentUrl { get; set; }
It should be `Url`. Also, please change this property name in other classes.

2023-05-05 06:04 UTC, gizemmutukurt commented
I am getting an error like this when running migration. It prevents me from testing.
![image](https://user-images.githubusercontent.com/99716457/236385132-cbd7e07c-1370-4d08-b5c8-f8cebe010e36.png)

2023-05-08 05:34 UTC, gizemmutukurt commented
For the clicked comment, the comment section in the community is not fully visible.

![1318781d-38dd-4df4-8f4a-ed2b3c7db5c7](https://user-images.githubusercontent.com/99716457/236742008-7fe7cb19-30f8-429b-b410-728326211b63.gif)

2023-05-08 06:24 UTC, ebicoglu commented
remove the offsetheight of the window
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight

2023-05-08 08:31 UTC, EngincanV approved these changes

2023-05-09 13:56 UTC, gizemmutukurt approved these changes

2023-05-09 13:56 UTC, merged