Script nonce support for CSP
abpframework/abp pull request #16496
Opened 2023-05-05 12:26 UTC by salihozkara

### Description

If someone wants to use the script nonce value within the scope of CSP, arrangements have been made in the abp framework so that there is no problem in the bundle system.

### Checklist

- [ ] I fully tested it as developer
- [ ] I documented it (or no need to document or I will create a separate documentation issue)

2023-05-05 13:07 UTC, salihozkara commented
Here are some potential changes that may break existing code: 

1. The string property ContentSecurityPolicyValue in the class AbpSecurityHeadersOptions has been removed and replaced with contentSecurityPolicyValueDictionary.
2. A new AbpNonceScriptTagHelper has been added, which will replace the script tag in HTML. If there is any C# code used inside the HTML tag, it may cause an error. For example, the usage `<script @string.empty>` will no longer work.

2023-05-06 06:05 UTC, EngincanV reviewed
Instead of introducing a new tag helper, can't we add a new property to the `abp-script` tag helper, as we did for *Defer*:

https://github.com/abpframework/abp/blob/c8199a2582f9e5302047b9c4360174e30e2e62a2/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bundling/Volo/Abp/AspNetCore/Mvc/UI/Bundling/TagHelpers/AbpScriptTagHelper.cs#L8-L9

If you do like this, you would not need to add a new property to `AbpSecurityHeadersOptions` and would not need to create a new tag helper. What do you think @salihozkara?

2023-05-06 15:54 UTC, salihozkara commented
> Instead of introducing a new tag helper, can't we add a new property to the `abp-script` tag helper, as we did for _Defer_:
> 
> https://github.com/abpframework/abp/blob/c8199a2582f9e5302047b9c4360174e30e2e62a2/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bundling/Volo/Abp/AspNetCore/Mvc/UI/Bundling/TagHelpers/AbpScriptTagHelper.cs#L8-L9
> 
> _Adding an property_:
> 
> ```cs
>  [HtmlAttributeName("nonce")] 
>  public bool Nonce { get; set; } 
> ```
> 
> If you do like this, you would not need to add a new property to `AbpSecurityHeadersOptions` and would not need to create a new tag helper.
> 
> Also, you would not need to inject the `IOptions<AbpSecurityHeadersOptions>` to `AbpTagHelperStyleService`.
> 
> What do you think @salihozkara?

The purpose of creating a script tag helper is to automatically add a nonce value to all scripts when `UseContentSecurityPolicyNonce` option is activated. By using this tag helper, the scripts will recognize it as the source of the nonce value when the user option is enabled. Otherwise, it would be necessary to manually modify all script tags.

2023-05-11 13:40 UTC, ebicoglu commented on framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/Security/AbpSecurityHeadersMiddleware.cs
> +        var contentSecurityPolicyValueDictionary = Options.Value.ContentSecurityPolicyValueDictionary.ToDictionary(x=>x.Key, x=>x.Value);
move the line 32 to 40

2023-05-11 13:42 UTC, ebicoglu commented on framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/Security/AbpSecurityHeadersMiddleware.cs
> +                    if (contentSecurityPolicyValueDictionary.TryGetValue("script-src", out var scriptSrc))
use ABP's `AddIfNotContains` extension method

2023-05-11 13:47 UTC, ebicoglu commented on framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/Security/AbpSecurityHeadersMiddleware.cs
> +        if (Options.Value.UseContentSecurityPolicyHeader && !Options.Value.IgnoredUrls.Any(x => context.Request.Path.StartsWithSegments(x.EnsureStartsWith('/'))))
use if guards

2023-05-11 13:48 UTC, ebicoglu commented on framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/Security/AbpSecurityHeadersMiddleware.cs
> +        if (Options.Value.UseContentSecurityPolicyHeader && !Options.Value.IgnoredUrls.Any(x => context.Request.Path.StartsWithSegments(x.EnsureStartsWith('/'))))
add extra if guard for only html document check for content type

2023-05-11 14:02 UTC, ebicoglu requested changes
check the requested content: if it's a plain HTML then don't add CSP header.
check this feature on Swagger, Hangfire

2023-05-12 10:55 UTC, hikalkan approved these changes

2023-05-15 15:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/abpframework/abp?pullRequest=16496) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/abpframework/abp?pullRequest=16496) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/abpframework/abp?pullRequest=16496) it.</sub>

2023-05-16 08:24 UTC, salihozkara commented
Ignore Elsa example:

```cs
Configure<AbpSecurityHeadersOptions>(o =>
{
        o.UseContentSecurityPolicyHeader = true;
        o.UseContentSecurityPolicyNonce = true;
        o.IgnoredNonceScriptSelectors.Add(context =>
        {
             var endpoint = context.GetEndpoint();
             return Task.FromResult(endpoint?.Metadata.GetMetadata<PageRouteMetadata>()?.RouteTemplate == "/{YOURHOSTPAGE}");
        });
});
```

2023-05-16 11:04 UTC, EngincanV approved these changes

2023-05-16 11:04 UTC, EngincanV commented on framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bundling/Volo/Abp/AspNetCore/Mvc/UI/Bundling/TagHelpers/AbpTagHelperStyleService.cs
> +    private readonly IOptions<AbpSecurityHeadersOptions> _securityHeadersOptions;
Here, you can use the class as follows:

```suggestion
    protected AbpSecurityHeadersOptions SecurityHeadersOptions { get; }
```

Then, change the [27th line](https://github.com/abpframework/abp/pull/16496/files#diff-59be621ab60b20a1194159c130e092748728730c1603afc2cde3a9379ca3474bR27) as follows:

```csharp
SecurityHeadersOptions = securityHeadersOptions.Value;
```

2023-05-16 11:04 UTC, EngincanV commented on framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/Security/AbpSecurityHeadersOptions.cs
> +    public Dictionary<string,IEnumerable<string>> ContentSecurityPolicyValues { get; }
```suggestion
    public Dictionary<string, IEnumerable<string>> ContentSecurityPolicyValues { get; }
```

2023-05-29 05:29 UTC, hikalkan approved these changes

2023-05-29 05:29 UTC, hikalkan approved these changes

2023-05-29 05:29 UTC, merged