Blogging - Improvements to member page and post detail page
abpframework/abp pull request #16503
Opened 2023-05-08 08:29 UTC by onurpicakci

![post-detail](https://user-images.githubusercontent.com/98148844/236775283-33c4d7d9-7177-4e4d-9611-923edc99081a.png)

![member-page](https://user-images.githubusercontent.com/98148844/236774679-08b97b68-8ce4-478f-9342-1f0e312c3488.png)

2023-05-08 11:18 UTC, gizemmutukurt commented
Can you explain what I will test? @onurpicakci

2023-05-09 05:27 UTC, gizemmutukurt commented
- [ ] An error is received when going to the "My profile" page.

![image](https://user-images.githubusercontent.com/99716457/237001606-3146cf00-eb30-403c-ba15-f36e5bb0f978.png)

- [ ] This part is confusing. When I looked, I thought that the user whose profile appeared should have their own posts. However, it does list the most recent posts.
![image](https://user-images.githubusercontent.com/99716457/237002040-0cc13b9a-9535-483b-b976-548d671348a0.png)

2023-05-10 13:53 UTC, gizemmutukurt approved these changes

2023-05-11 08:51 UTC, salihozkara requested changes

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUser.cs
> +        public string WebSite { get; set; }
Please use the virtual keyword

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUser.cs
> +        public string Twitter { get; set; }
Please use the virtual keyword

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUser.cs
> +        public string Github { get; set; }
Please use the virtual keyword

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUser.cs
> +        public string Linkedin { get; set; }
Please use the virtual keyword

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUser.cs
> +        public string Company { get; set; }
Please use the virtual keyword

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUser.cs
> +        public string JobTitle { get; set; }
Please use the virtual keyword

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUser.cs
> +        public string Biography { get; set; }
Please use the virtual keyword

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUser.cs
> +        [CanBeNull]
No need for CanBeNull attributes

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUser.cs
> +        [CanBeNull]
No need for CanBeNull attributes

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUser.cs
> +        [CanBeNull]
No need for CanBeNull attributes

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUser.cs
> +        [CanBeNull]
No need for CanBeNull attributes

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUser.cs
> +        [CanBeNull]
No need for CanBeNull attributes

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUser.cs
> +        [CanBeNull]
No need for CanBeNull attributes

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUser.cs
> +        [CanBeNull]
No need for CanBeNull attributes

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Web/Pages/Blogs/Posts/Detail.cshtml.cs
> +            LatestPosts = (await _postAppService.GetListByBlogIdAndTagNameAsync(Blog.Id, TagName)).Items;
- [ ] Limit to number instead of fetching all posts.
- [ ] Is there a guarantee that you will bring the latest posts? Otherwise, write a new method

2023-05-11 08:51 UTC, salihozkara commented on modules/blogging/src/Volo.Blogging.Web/Pages/Members/Index.js
> +        console.log("asdasdsa")
Delete here

2023-05-15 11:11 UTC, ebicoglu approved these changes

2023-05-15 11:27 UTC, salihozkara approved these changes

2023-05-15 11:55 UTC, merged