connection status service was using rxjs observable now we also add s…
abpframework/abp pull request #17054
Opened 2023-07-06 12:06 UTC by Sinan997

Resolves #17008 

### Description

#17008 is already resolved but we are adding a signal alternative instead of using rxjs

2023-07-06 12:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/abpframework/abp?pullRequest=17054) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/abpframework/abp?pullRequest=17054) before we can accept your contribution.<br/><hr/>**Sinan997** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/abpframework/abp?pullRequest=17054) it.</sub>

2023-07-06 12:11 UTC, masumulu28 commented on npm/ng-packs/packages/theme-shared/src/lib/components/internet-connection-status/internet-connection-status.component.ts
> +  imports:[NgIf, AsyncPipe, LocalizationModule],
If we gonna use signal, don't need to import `AsyncPipe`

2023-07-07 11:31 UTC, masumulu28 commented on npm/ng-packs/packages/core/src/lib/services/internet-connection-service.ts
>    /* returns OBSERVABLE */
No need comment

2023-07-07 11:31 UTC, masumulu28 commented on npm/ng-packs/packages/core/src/lib/services/internet-connection-service.ts
> +  /* READONLY ANGULAR SIGNAL */
No need comment

2023-07-07 12:00 UTC, masum-ulu commented on docs/en/UI/Angular/Internet-Connection-Service.md
> +```
There is missing content type here. Please add **js** key to display much better content 

### Example

```js
import { Injectable } from  '@angular/core';

@Injectable({ providedIn: 'root' }) 
export  class  InternetConnectionService {}
```

2023-07-07 12:56 UTC, masum-ulu commented on docs/en/UI/Angular/Internet-Connection-Service.md
>  ### internet-connection-service.ts
There are a few bad UI please format example service 

![image](https://github.com/abpframework/abp/assets/49063256/e9a6b30f-5893-44d7-a3c0-b70aeb074d9e)

2023-07-10 08:52 UTC, rqx110 commented
`Signal` is still a developer preview feature(angular 16).  and we have not migrate to `Signal`. 
do we need merge this to **7.4-preview** milestone?

https://github.com/abpframework/abp/issues/16670

2023-07-21 06:32 UTC, mahmut-gundogdu commented
> `Signal` is still a developer preview feature(angular 16). and we have not migrate to `Signal`. do we need merge this to **7.4-preview** milestone?
> 
> #16670

Signal is developer preview yes. But it is simple component and we appened to source code, so if the user want to change , the user can do that.  Also the pr will released 4 weeks later, I think, Signal will marked as Stable.

for a dev = 7.4 preview now. We didn't create a 7.4 branch. I thought the PR target branch was right.

2023-07-21 06:35 UTC, mahmut-gundogdu requested changes

2023-07-21 06:35 UTC, mahmut-gundogdu commented on npm/ng-packs/packages/core/src/lib/tests/internet-connection.service.spec.ts
> +    expect(typeof !service.networkStatus()).toEqual('boolean')
The test is pointless

2023-07-21 06:35 UTC, mahmut-gundogdu commented on npm/ng-packs/packages/core/src/lib/tests/internet-connection.service.spec.ts
> +      expect(typeof val).toEqual('boolean')
you should control with test default value is correct and when you set a value, it should be equal to your value.

2023-07-21 06:35 UTC, mahmut-gundogdu commented on npm/ng-packs/packages/theme-shared/src/lib/components/internet-connection-status/internet-connection-status.component.ts
> +  isOnline = this.internetConnectionService.networkStatus
you can use signal compute or converting opposite of value.  it just a note. it works like that.

2023-07-27 13:08 UTC, mahmut-gundogdu approved these changes

2023-07-28 07:21 UTC, masumulu28 commented on docs/en/UI/Angular/Internet-Connection-Service.md
> +class someComponent{
class name must be [PascalCase](https://www.theserverside.com/definition/Pascal-case)

2023-07-28 07:21 UTC, masumulu28 commented on docs/en/UI/Angular/Internet-Connection-Service.md
> +class someComponent{
class name must be [PascalCase](https://www.theserverside.com/definition/Pascal-case)

2023-07-28 07:21 UTC, masumulu28 commented on docs/en/UI/Angular/Internet-Connection-Service.md
> +### internet-connection-service.ts
Remove this service section

2023-08-11 15:07 UTC, braim23 approved these changes

2023-08-11 16:14 UTC, merged