Password Complexity Indicator doc
abpframework/abp pull request #17112
Opened 2023-07-13 18:53 UTC by Sinan997

doc

2023-07-25 12:06 UTC, mahmut-gundogdu commented on docs/en/UI/Angular/Password-Complexity-Indicator.md
> +  colors: string[] = [
where os the class name ? the code is broken

2023-07-25 12:06 UTC, mahmut-gundogdu commented on docs/en/UI/Angular/Password-Complexity-Indicator.md
> +- **but remember if you change the requirements, it's length must be equal with the colors array**
Dokuman must be simplified

2023-07-27 15:03 UTC, braim23 approved these changes

2023-08-10 08:54 UTC, mahmut-gundogdu requested changes
Move the docs 
https://github.com/abpio/abp-commercial-docs

2023-08-10 11:08 UTC, masumulu28 commented
I'm closing this PR because the document must be in commercial repository. @Sinan997 will move the document

2023-08-10 11:08 UTC, closed without merging