Handle CmsKit Pages routing in a Middleware
abpframework/abp pull request #17642
Opened 2023-09-14 14:48 UTC by enisn

### Description

Resolves https://github.com/abpframework/abp/issues/17319

This PR moves route handling logic to a middleware instead registering a very generic route pattern to ASP.NET routing logic.
You can see the disadvantages of this logic in issue #17279 

In the new logic, CmsKit Pages feature doesn't handle all the URLs, such as Error pages and some other dynamic paths. It handles only 404 pages in the middleware and checks if any page wişth that path (slug) and don't do anything if there is no such a page. In the previous logic all the requests _(including 404 results)_ used to end in Pages/Index.razor page. It was handling all the requests.

- ✅ Compatible with replacing home page (`/`) feature
- ✅ Compatible with [URL Forwarding](https://docs.abp.io/en/commercial/latest/modules/cms-kit/url-forwarding) feature.
- 
### Checklist

- [x] I fully tested it as developer / designer and created unit / integration tests
- [x] I documented it (or no need to document or I will create a separate documentation issue)

### How to test it?

Please describe how this can be tested by the test engineers if it is not already explicit - or remove this section if no need to description.

2023-09-15 08:02 UTC, enisn commented
**TODO**
- [ ] Add caching for pages

2023-09-19 09:15 UTC, hikalkan requested changes

2023-09-19 09:15 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.Common.Application/Volo/CmsKit/Pages/PageChangedHandler.cs
> +    public Task RemoveFromCacheAsync(string slug)
Can be private

2023-09-19 09:15 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.Domain/Volo/CmsKit/Pages/PageCacheKey.cs
> +        return $"Page_{Slug}";
```suggestion
        return $"CmsPage_{Slug}";
```

2023-09-19 09:15 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.Common.Application/Volo/CmsKit/Pages/PageChangedHandler.cs
> +        return RemoveFromCacheAsync(eventData.Entity.Slug);
Think that again, it can't work.

2023-09-19 09:15 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.Public.Application/Volo/CmsKit/Public/Pages/PagePublicAppService.cs
> +        return await PageRepository.ExistsAsync(slug);
Instead of using repository, use the same cache logic of `FindBySlugAsync`.

2023-09-19 09:15 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.Public.Web/CmsKitPagesMiddlewareExtensions.cs
> +        return builder.UseMiddleware<PageRoutingMiddleware>();
https://github.com/abpframework/abp/blob/fec388d4c5be8e135bc182b97ff87000c27b50ab/framework/src/Volo.Abp.AspNetCore/Microsoft/AspNetCore/Builder/AbpApplicationBuilderExtensions.cs#L94C7-L94C7

2023-09-19 09:15 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.Public.HttpApi/Volo/CmsKit/Public/Pages/PagesPublicController.cs
> +    [Route("{slug}/exist")]
`/` in `slug` values can be a problem here.

2023-09-19 09:15 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.Public.Web/CmsKitPagesMiddlewareExtensions.cs
> +        return builder.UseMiddleware<PageRoutingMiddleware>();
https://github.com/abpframework/abp/blob/dev/modules/cms-kit/src/Volo.CmsKit.Public.Web/CmsKitPublicWebModule.cs should not add middleware

2023-09-19 09:15 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.Public.Web/CmsKitPublicWebModule.cs
> +            app.UseCmsKitPagesMiddleware();
Should not add middleware in modules

2023-09-19 09:15 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.Public.Web/PageRoutingMiddleware.cs
> +                context.Request.Path = $"/pages/{slug}";
Instead, try to implement with endpoint mapping.

2023-09-26 11:47 UTC, hikalkan commented on modules/cms-kit/src/Volo.CmsKit.Public.HttpApi/Volo/CmsKit/Public/Pages/PagesPublicController.cs
> +    [Route("check")]
```suggestion
    [Route("exists")]
```

2023-09-26 12:54 UTC, hikalkan approved these changes

2023-09-26 12:54 UTC, merged

2023-10-03 13:07 UTC, maliming commented
This route catches all requests(`Pages/...`) to this page.

![image](https://github.com/abpframework/abp/assets/6908465/b4cbf284-803e-4331-bd6f-0cde81e1a609)

2023-10-03 13:10 UTC, enisn commented
Yes, it's for backward compatibility, in the previous version page routes works as the same URL:
https://github.com/abpframework/abp/blob/c97e085546b90a42ffb285660a6ca04a3d769c0e/modules/cms-kit/src/Volo.CmsKit.Public.Web/CmsKitPublicWebModule.cs#L84

2023-10-03 13:11 UTC, enisn commented
Ok I see
![image](https://github.com/abpframework/abp/assets/23705418/f963e93a-2471-49a6-9eef-9e4bcfb8ee57)


We can ignore backward compatibility or use only /page/{slug}