Create an introductory post for CMS Kit Demo application
abpframework/abp pull request #17718
Opened 2023-09-23 12:11 UTC by EngincanV

Resolves https://github.com/volosoft/vs-internal/issues/2836

---

I am not ensure about the title, I think we can find a more attractive one. Here are some alternatives:

* "Unleash the Power of ABP CMS Kit: A Dynamic Content Showcase”
* “Build your own dynamic content website with ABP CMS Kit”

I am open to suggestions.

2023-09-25 04:44 UTC, braim23 approved these changes

2023-09-25 04:48 UTC, braim23 commented
I suggest the following as the title:
"ABP's CMS Kit: Explore the Source Code of the Dynamic Content Masterpiece"

2023-09-25 06:47 UTC, hikalkan requested changes

2023-09-25 06:47 UTC, hikalkan commented on docs/en/Community-Articles/2023-09-23-CMS-Kit-Demo/POST.md
> +The following features are provided by the CMS Kit Pro Module:
```suggestion
CMS Kit Pro is a part of [ABP Commercial](https://commercial.abp.io/) and provides additional features. The following features are provided by the CMS Kit Pro Module: 
```

2023-09-25 06:47 UTC, hikalkan commented on docs/en/Community-Articles/2023-09-23-CMS-Kit-Demo/POST.md
> +Please try the CMS Kit Module now and provide [feedback](https://github.com/abpframework/abp) to help us to build a more effective content management kit!
We can add a resources section with the following links:

* demo source code link
* demo lşive link
* cms kit document link
* cms kit pro document link

2023-09-25 06:47 UTC, hikalkan commented
I liked "Unleash the Power of ABP CMS Kit: A Dynamic Content Showcase"

2023-09-25 08:02 UTC, enisn approved these changes

2023-09-28 06:54 UTC, hikalkan approved these changes

2023-09-28 06:54 UTC, merged