Remove Permissions and other user-related data when deleting a user.
abpframework/abp pull request #18051
Opened 2023-11-02 03:31 UTC by maliming

Resolves #18042

2023-11-02 08:49 UTC, rqx110 commented on modules/setting-management/src/Volo.Abp.SettingManagement.Application/Volo/Abp/SettingManagement/UserDeletedEventHandler.cs
> +        await SettingManager.DeleteAsync(UserPermissionValueProvider.ProviderName, eventData.Entity.Id.ToString());
```suggestion
        await SettingManager.DeleteAsync(UserSettingValueProvider.ProviderName, eventData.Entity.Id.ToString());
```

2023-11-05 15:40 UTC, hikalkan requested changes

2023-11-05 15:40 UTC, hikalkan commented on modules/identity/src/Volo.Abp.PermissionManagement.Domain.Identity/Volo/Abp/PermissionManagement/Identity/UserDeletedEventHandler.cs
> +    public async Task HandleEventAsync(EntityDeletedEto<UserEto> eventData)
Since `PermissionManager` is a domain service (that doesn't manage UOW), it is better to make that method UOW (and virtual).

2023-11-05 15:40 UTC, hikalkan commented on modules/setting-management/src/Volo.Abp.SettingManagement.Application/Volo/Abp/SettingManagement/UserDeletedEventHandler.cs
> +    public async Task HandleEventAsync(EntityDeletedEto<UserEto> eventData)
We can make that method UOW too.

2023-11-06 06:39 UTC, hikalkan approved these changes

2023-11-06 06:39 UTC, merged