Add and update unit tests
abpframework/abp pull request #18058
Opened 2023-11-03 14:04 UTC by Sinan997

Resolves #18054

2023-11-06 07:19 UTC, mahmut-gundogdu requested changes

2023-11-06 07:19 UTC, mahmut-gundogdu commented on npm/ng-packs/packages/core/src/lib/services/http-error-reporter.service.ts
> +  reportError(error: HttpErrorResponse) {
make sure it does not cause any error.

2023-11-06 08:41 UTC, Sinan997 commented on npm/ng-packs/packages/core/src/lib/services/http-error-reporter.service.ts
> +  reportError(error: HttpErrorResponse) {
it works fine

2023-11-06 13:20 UTC, mahmut-gundogdu approved these changes

2023-11-07 12:52 UTC, masumulu28 commented on npm/ng-packs/packages/core/src/lib/tests/permission.guard.spec.ts
> +  };
Is that a true mocking method ? Can we provide another way for mocking a service ? It seems like duplicated in DummyComponent 🤔 ?

2023-11-10 06:29 UTC, masumulu28 approved these changes

2023-11-10 06:29 UTC, merged