Grant all permissions checkbox does not affect Select all checkbox.
abpframework/abp pull request #18429
Opened 2023-12-11 09:07 UTC by Sinan997

[#15934](https://github.com/volosoft/volo/issues/15934)  Resolves
 
![selectall](https://github.com/abpframework/abp/assets/72804437/c7395cf9-81ea-4a48-8817-9e8e68acdb29)

2023-12-11 09:18 UTC, masumulu28 approved these changes

2023-12-11 11:11 UTC, gizemmutukurt commented
- [x] If there is only one option and it is removed, it should be removed in select all.
![image](https://github.com/abpframework/abp/assets/99716457/5ad81568-4510-4530-8e3a-208dc1207686)

- [x] If there are many selections and some have been removed, select all should be "-".
![image](https://github.com/abpframework/abp/assets/99716457/2e5cc743-4a2e-490d-bc86-8fd22df3579c)

2023-12-11 11:12 UTC, gizemmutukurt requested changes
It will be checked again when the problems are fixed.

2023-12-11 13:31 UTC, gizemmutukurt commented
The following situations need to be corrected.

![image](https://github.com/abpframework/abp/assets/99716457/eb3c1260-84ec-41d8-a761-ca3f84a749f5)
![image](https://github.com/abpframework/abp/assets/99716457/498d6bbf-fb8f-48a4-9f63-7bc96f75cf5e)

2023-12-12 05:11 UTC, gizemmutukurt approved these changes

2023-12-12 05:11 UTC, merged