Cmskit menuitem page relation
abpframework/abp pull request #18782
Opened 2024-01-17 09:16 UTC by enisn

### Description

Part of https://github.com/volosoft/vs-internal/issues/3588

With this PR, MenuItem and Page have a better relationship. 
- URL field is required now.
- When a page is related to a menu item, URL can't be changed manually.
- Related page of menu item will be initialized as selected in the update modal.
- When Page feature is disabled, there will be no Page tab on menu item modal

Required fields:
![image](https://github.com/abpframework/abp/assets/23705418/be9cd508-ca87-45e9-a19e-8ea90f70ae78)

When a page is selected:
![image](https://github.com/abpframework/abp/assets/23705418/f194a43e-3bf3-461d-b54f-3aac80da6eab)

| Page Feature Disabled | Enabled |
| --- | --- |
| ![image](https://github.com/abpframework/abp/assets/23705418/f552a77a-d0ed-4266-9718-47c11545978f) | ![image](https://github.com/abpframework/abp/assets/23705418/1d2d6a51-65b5-4412-bd8b-13d58b2b06ef) |

### Checklist

- [x] I fully tested it as developer / designer and created unit / integration tests
- [x] I documented it (or no need to document or I will create a separate documentation issue)

### How to test it?

Please describe how this can be tested by the test engineers if it is not already explicit - or remove this section if no need to description.

2024-01-18 11:35 UTC, enisn commented
Tests are passing now, 
![image](https://github.com/abpframework/abp/assets/23705418/65926140-dbd0-432e-9606-dd82b053c9c8)

There is rate-limiting problem in the pipeline
![image](https://github.com/abpframework/abp/assets/23705418/96806fab-4579-40d8-afc6-727c4ed22668)

2024-01-22 06:40 UTC, enisn commented
the broken test isn't related to the changes in this PR

![image](https://github.com/abpframework/abp/assets/23705418/23a1b627-9f5f-404e-a0a2-3f6006d8a849)

2024-01-22 14:41 UTC, oykuermann requested changes
I'll check after the changes: https://github.com/volosoft/volo/pull/16457#issuecomment-1903945541

2024-01-23 11:49 UTC, oykuermann approved these changes

2024-01-23 11:50 UTC, oykuermann commented
I'm waiting for @realLiangshiwei 's review to merge this PR.

2024-01-23 11:56 UTC, realLiangshiwei commented on modules/cms-kit/src/Volo.CmsKit.MongoDB/Volo/CmsKit/MongoDB/Pages/MongoPageRepository.cs
> +    public async Task<string> FindTitleAsync(Guid pageId, CancellationToken cancellationToken = default)
Task<string?>

2024-01-23 12:03 UTC, enisn commented on modules/cms-kit/src/Volo.CmsKit.MongoDB/Volo/CmsKit/MongoDB/Pages/MongoPageRepository.cs
> +    public async Task<string> FindTitleAsync(Guid pageId, CancellationToken cancellationToken = default)
Solved by https://github.com/abpframework/abp/commit/2184b532c5881c48fd756a574d7f9aa29b8f8c73

2024-01-23 12:25 UTC, realLiangshiwei approved these changes

2024-01-23 12:42 UTC, merged