Blazor full stack web UI
abpframework/abp pull request #18876
Opened 2024-01-29 09:42 UTC by maliming

2024-01-31 12:33 UTC, GadiZimerman commented
@CodiumAI-Agent /describe

2024-01-31 12:34 UTC, GadiZimerman commented
@CodiumAI-Agent /review

2024-01-31 12:35 UTC, CodiumAI-Agent commented
## PR Analysis

### (review updated until commit https://github.com/abpframework/abp/commit/cb37ba63a006798243c13239912993ba2f1416a3)


- 🎯 **Main theme:** Adding support for Blazor Full-Stack Web App
- 📝 **PR summary:** This PR adds support for Blazor Full-Stack Web App. It includes changes in multiple files, mainly in the `MyProjectNameBlazorModule.cs` and `MyProjectNameBlazorClientModule.cs` files. The PR also includes changes in the `BundlingService.cs` and `AbpModuleHelper.cs` files.
- 📌 **Type of PR:** Enhancement
- 🧪 **Relevant tests added:** No
- ⏱️ **Estimated effort to review [1-5]:** 4, because the PR includes changes in multiple files and the changes are quite extensive. It requires a good understanding of the Blazor Full-Stack Web App to review this PR.
## PR Feedback



<strong>💡 General suggestions:</strong> The PR is well-structured and the changes are logically grouped. However, it would be beneficial to include tests to ensure the new functionality works as expected. Also, it would
<hr>

<details> <summary><strong>✨ Usage guide:</strong></summary><hr> 

**Overview:**
The `review` tool scans the PR code changes, and generates a PR review. The tool can be triggered [automatically](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) every time a new PR is opened, or can be invoked manually by commenting on any PR.
When commenting, to edit [configurations](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L19) related to the review tool (`pr_reviewer` section), use the following template:
```
/review --pr_reviewer.some_config1=... --pr_reviewer.some_config2=...
```
With a [configuration file](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-with-github-app), use the following template:
```
[pr_reviewer]
some_config1=...
some_config2=...
```
    

<table><tr><td><details> <summary><strong> Utilizing extra instructions</strong></summary><hr>

The `review` tool can be configured with extra instructions, which can be used to guide the model to a feedback tailored to the needs of your project.

Be specific, clear, and concise in the instructions. With extra instructions, you are the prompter. Specify the relevant sub-tool, and the relevant aspects of the PR that you want to emphasize.

Examples for extra instructions:
```
[pr_reviewer] # /review #
extra_instructions="""
In the code feedback section, emphasize the following:
- Does the code logic cover relevant edge cases?
- Is the code logic clear and easy to understand?
- Is the code logic efficient?
...
"""
```
Use triple quotes to write multi-line instructions. Use bullet points to make the instructions more readable.
        

</details></td></tr>

<tr><td><details> <summary><strong> How to enable\disable automation</strong></summary><hr>

- When you first install PR-Agent app, the [default mode](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) for the `review` tool is:
```
pr_commands = ["/review", ...]
```
meaning the `review` tool will run automatically on every PR, with the default configuration.
Edit this field to enable/disable the tool, or to change the used configurations
        

</details></td></tr>

<tr><td><details> <summary><strong> About the 'Code feedback' section</strong></summary><hr>

The `review` tool provides several type of feedbacks, one of them is code suggestions.
If you are interested **only** in the code suggestions, it is recommended to use the [`improve`](./IMPROVE.md) feature instead, since it dedicated only to code suggestions, and usually gives better results.
Use the `review` tool if you want to get a more comprehensive feedback, which includes code suggestions as well.


</details></td></tr>

<tr><td><details> <summary><strong> Auto-labels</strong></summary><hr>

The `review` tool can auto-generate two specific types of labels for a PR:
- a `possible security issue` label, that detects possible [security issues](https://github.com/Codium-ai/pr-agent/blob/tr/user_description/pr_agent/settings/pr_reviewer_prompts.toml#L136) (`enable_review_labels_security` flag)
- a `Review effort [1-5]: x` label, where x is the estimated effort to review the PR (`enable_review_labels_effort` flag)


</details></td></tr>

<tr><td><details> <summary><strong> Extra sub-tools</strong></summary><hr>

The `review` tool provides a collection of possible feedbacks about a PR.
It is recommended to review the [possible options](https://github.com/Codium-ai/pr-agent/blob/main/docs/REVIEW.md#enabledisable-features), and choose the ones relevant for your use case.
Some of the feature that are disabled by default are quite useful, and should be considered for enabling. For example: 
`require_score_review`, `require_soc2_review`, `enable_review_labels_effort`, and more.


</details></td></tr>



<tr><td><details> <summary><strong> More PR-Agent commands</strong></summary><hr> 

> To invoke the PR-Agent, add a comment using one of the following commands:  
> - **/review**: Request a review of your Pull Request.   
> - **/describe**: Update the PR title and description based on the contents of the PR.   
> - **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   
> - **/ask \<QUESTION\>**: Ask a question about the PR.   
> - **/update_changelog**: Update the changelog based on the PR's contents.   
> - **/add_docs** 💎: Generate docstring for new components introduced in the PR.   
> - **/generate_labels** 💎: Generate labels for the PR based on the PR's contents.   
> - **/analyze** 💎: Automatically analyzes the PR, and presents changes walkthrough for each component.   

>See the [tools guide](https://github.com/Codium-ai/pr-agent/blob/main/docs/TOOLS_GUIDE.md) for more details.
>To list the possible configuration parameters, add a **/config** comment.   
 


</details></td></tr>

</table>

See the [review usage](https://github.com/Codium-ai/pr-agent/blob/main/docs/REVIEW.md) page for a comprehensive guide on using this tool.


</details>

2024-01-31 12:35 UTC, CodiumAI-Agent commented
**[Persistent review](https://github.com/abpframework/abp/pull/18876#issuecomment-1919021589)** updated to latest commit https://github.com/abpframework/abp/commit/cb37ba63a006798243c13239912993ba2f1416a3

2024-02-02 19:25 UTC, jonathan-np-dev commented
Do you know when this will be released? Is it possible to build the entire code base from your repo and get started that way? I really want to use the new template :)

2024-02-22 07:16 UTC, enisn commented
We tried to create Blazor WebApp with local CLI build:

```
 dotnet volo.Abp.Cli.dll new BlazorWebAppTest -t app --version 8.1.0-rc.1 -csf -tv -u blazor-webapp
```

There are no Blazor Web App projects in the solution
![image](https://github.com/abpframework/abp/assets/23705418/b79199db-459f-425e-a4db-67e2309bcf59)

2024-02-22 07:17 UTC, maliming commented
You need to replace your local template zip with the current branch.

> We tried to create Blazor WebApp with local CLI build:
> 
> ```
>  dotnet volo.Abp.Cli.dll new BlazorWebAppTest -t app --version 8.1.0-rc.1 -csf -tv -u blazor-webapp
> ```
> 
> There are no Blazor Web App projects in the solution ![image](https://private-user-images.githubusercontent.com/23705418/306900983-b79199db-459f-425e-a4db-67e2309bcf59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1ODY1MTEsIm5iZiI6MTcwODU4NjIxMSwicGF0aCI6Ii8yMzcwNTQxOC8zMDY5MDA5ODMtYjc5MTk5ZGItNDU5Zi00MjVlLWE0ZGItNjdlMjMwOWJjZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA3MTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NDM4Nzg3NzA5ODQ4NWZiMmE4ZGExMzFlNGQzMjY4YTY3NGMzMjk3MDgzZmEyMTk3OTAxMDBiMTUyMTEyOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jhqbDOeuf1OWtFrWYKiwGyhTYZcRaA_SJ8C4e4XI9U4)

2024-02-22 07:58 UTC, berkansasmaz requested changes
Add a semicolon before every code block as below:

[Your sentence]: 

```csharp
code block
```

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +# New Blazor Web App Template in ABP 8.2
```suggestion
# Migrating to Blazor Web App
```

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +ABP 8.2 supports the new Blazor Web App template, In this guide, we will introduce some new changes and features in the new Blazor Web App template.
```suggestion
ABP v8.2.x supports the new Blazor Web App template, in this guide, we will introduce some new changes and features in the new Blazor Web App template.
```

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +Of course, you can also create Blazor wasm and Blazor Server applications. We have changed them to use the new Blazor Web App mode.
```suggestion
Of course, you can also create Blazor WASM and Blazor Server applications. We have changed them to use the new Blazor Web App mode:
```

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +The new Web App template has two project, each of them contains a system of abp modules.
```suggestion
The new Web App template has two projects, each containing a system of [ABP modules](https://docs.abp.io/en/abp/latest/Modules/Index).
```

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +The `Blazor.WebApp` is the startup project, There is a `App.razor` component in the `Blazor.WebApp` project, which is the root component of the Blazor application.
```suggestion
The `Blazor.WebApp` is the startup project, and there is an `App.razor` component in the `Blazor.WebApp` project, which is the root component of the Blazor application.
```

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +The main differences between it and a regular blazor server project are:
```suggestion
The main differences between it, and a regular Blazor server project are:
```

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +1. You need to `PreConfigure` the `AbpAspNetCoreComponentsWebOptions's IsBlazorWebApp` to `true`.
```suggestion
1. You need to `PreConfigure` the `IsBlazorWebApp` to `true` in `AbpAspNetCoreComponentsWebOptions`:
```

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +2. Add related services to the container. Add `MyProjectNameBlazorClientModule's` assembly to the `AbpRouterOptions's AdditionalAssemblies`.
```suggestion
2. Add related services to the container. Add assembly of `MyProjectNameBlazorClientModule` to the `AdditionalAssemblies` by configuring `AbpRouterOptions`:
```

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +# New Blazor Web App Template in ABP 8.2
Also, change the file name to "Migrating-to-Blazor-Web-App"

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +The main differences between it and a regular blazor wasm project are:
```suggestion
The main differences between it and a regular Blazor WASM project are:
```

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +1. You need to `PreConfigure` the `AbpAspNetCoreComponentsWebOptions's IsBlazorWebApp` to `true`.
```suggestion
1. You need to `PreConfigure` the `IsBlazorWebApp` to `true` in `AbpAspNetCoreComponentsWebOptions`:
```

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +2. Use `AddBlazorWebAppServices` to replace `Authentication` code.
```suggestion
2. Use `AddBlazorWebAppServices` to replace `Authentication` code:
```

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +`App.rzor` of `MyCompanyName.MyProjectName.Blazor.WebApp.Tiered`:
```suggestion
Add code block to `App.razor` of `MyCompanyName.MyProjectName.Blazor.WebApp.Tiered` as below:
```

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +`MyProjectNameBlazorClientModule` of `MyCompanyName.MyProjectName.Blazor.WebApp.Tiered.Client`:
```suggestion
Add `ConfigureAuthentication` to `MyProjectNameBlazorClientModule` of `MyCompanyName.MyProjectName.Blazor.WebApp.Tiered.Client` as below:
```

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +For Blazor wasm and Blazor Server applications, you need to set `IsBlazorWebApp` to `true` and not need change the `InteractiveAuto`.
```suggestion
For Blazor WASM and Blazor Server applications, you need to set `IsBlazorWebApp` to `true` and not need to change the `InteractiveAuto`:
```

2024-02-22 07:58 UTC, berkansasmaz commented on docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md
> +You need set `IsBlazorWebApp` and `InteractiveAuto` to `true` in the `appsettings.json` file of the `MyCompanyName.MyProjectName.Blazor.WebApp.Client` project.
```suggestion
You need set `IsBlazorWebApp` and `InteractiveAuto` to `true` in the `appsettings.json` file of the `MyCompanyName.MyProjectName.Blazor.WebApp.Client` project:
```

2024-03-04 06:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/abpframework/abp?pullRequest=18876) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/abpframework/abp?pullRequest=18876) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: maliming<br/>:white_check_mark: enisn<br/>:x: github-actions[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/abpframework/abp?pullRequest=18876) it.</sub>

2024-03-04 07:57 UTC, merged