Index url controls added
abpframework/abp pull request #18922
Opened 2024-02-02 14:37 UTC by honurbu

Resolves https://github.com/abpframework/abp/issues/18447

https://github.com/abpframework/abp/assets/78691441/0f1f1eb7-4a7c-4779-8786-975170613079

2024-02-05 06:26 UTC, berkansasmaz approved these changes

2024-02-05 09:29 UTC, oykuermann commented
![image](https://github.com/abpframework/abp/assets/142304401/129c7cdb-4087-4de8-828d-6aa72fa7e788)
It did not work for /index endpoint.

2024-02-05 13:52 UTC, oykuermann requested changes
I'll check after changes

2024-02-06 11:19 UTC, berkansasmaz approved these changes

2024-02-06 12:16 UTC, oykuermann approved these changes

2024-02-06 12:18 UTC, merged