Remove striped-rows from tables
abpframework/abp pull request #18941
Opened 2024-02-05 14:06 UTC by enisn

### Description

Closes https://github.com/abpframework/abp/issues/18906

### Checklist

- [x] I fully tested it as developer / designer and created unit / integration tests
- [x] I documented it (or no need to document or I will create a separate documentation issue)

### How to test it?

Please describe how this can be tested by the test engineers if it is not already explicit - or remove this section if no need to description.

2024-02-05 14:14 UTC, Sinan997 approved these changes

2024-02-06 07:48 UTC, oykuermann commented
- [ ] Mvc - On light theme (every table), the stripped-table view was not removed:
![image](https://github.com/abpframework/abp/assets/142304401/a916e998-73ff-4fc1-942a-9e5676660eed)
![image](https://github.com/abpframework/abp/assets/142304401/41c62024-d0ea-4fc3-89cb-fc96edfc1fa0)

- [ ] Blazor Server & Blazor Web Assembly - On light theme, Security Logs stripped-table view was not removed:
![image](https://github.com/abpframework/abp/assets/142304401/9c1c4b71-9181-40f3-a874-f95667fcba00)

2024-02-06 07:49 UTC, oykuermann requested changes
I'll check after changes

2024-02-06 11:04 UTC, oykuermann approved these changes

2024-02-06 11:05 UTC, merged