Page Titles Enhancement
abpframework/abp pull request #19022
Opened 2024-02-14 10:38 UTC by Sinan997

![image](https://github.com/abpframework/abp/assets/72804437/5daeb271-6db1-4467-97c7-482f96aad9a2)
![image](https://github.com/abpframework/abp/assets/72804437/09ed085d-1c4a-482a-8500-3547c158eec4)

2024-02-14 10:47 UTC, masumulu28 commented on npm/ng-packs/packages/core/src/lib/services/title-strategy.service.ts
> +// .pipe(tap(() => this.updateTitle(this.routerState))).subscribe();
Really :) ?

2024-02-14 11:02 UTC, Sinan997 commented on npm/ng-packs/packages/core/src/lib/services/title-strategy.service.ts
> +// .pipe(tap(() => this.updateTitle(this.routerState))).subscribe();
i must remove comment lines 😄

2024-02-14 12:04 UTC, masumulu28 commented
I'm checking on my local wait for approvment

2024-02-14 12:42 UTC, masumulu28 approved these changes

2024-02-14 13:54 UTC, oykuermann requested changes
I'll check after changes: https://github.com/volosoft/volo/pull/16718#issuecomment-1943812163

2024-02-15 11:46 UTC, oykuermann approved these changes

2024-02-15 11:46 UTC, merged