ProjectDeletionWarningMessage added to localization
abpframework/abp pull request #19061
Opened 2024-02-16 13:36 UTC by honurbu

Resolve https://github.com/volosoft/vs-internal/issues/3776

New message popup
![image](https://github.com/abpframework/abp/assets/78691441/fd3f2686-261b-4b71-acac-9b725e63f424)

2024-02-16 13:53 UTC, salihozkara approved these changes

2024-02-19 05:06 UTC, gizemmutukurt requested changes
```
Are you sure?
Project will be deleted.
```
It might be nicer to update the text this way.

2024-02-19 06:41 UTC, honurbu commented
![image](https://github.com/abpframework/abp/assets/78691441/953e4199-3f10-4f08-9aac-233258a06f5a)

2024-02-19 07:39 UTC, gizemmutukurt approved these changes

2024-02-19 07:39 UTC, merged