Localization improved for pricing page
abpframework/abp pull request #19126
Opened 2024-02-23 11:06 UTC by honurbu

Turkish
![image](https://github.com/abpframework/abp/assets/78691441/afd9545e-f5cb-4e6a-955a-d184ada187aa)

License name does not change across languages
![image](https://github.com/abpframework/abp/assets/78691441/d196cce2-bc0d-4881-aa86-ff450b41163d)

2024-02-23 14:01 UTC, salihozkara approved these changes

2024-02-26 12:22 UTC, oykuermann requested changes
![image](https://github.com/abpframework/abp/assets/142304401/4b510ac2-7fc8-4d6c-bfd9-abccf6c52ecf)
![image](https://github.com/abpframework/abp/assets/142304401/048b6fd2-93f0-4245-921b-36abb1bbe2eb)
![image](https://github.com/abpframework/abp/assets/142304401/6d7124da-eeea-43bb-9da0-d303fd4b63b9)

2024-02-27 08:46 UTC, oykuermann commented
- [ ] ![image](https://github.com/abpframework/abp/assets/142304401/c777eb1e-ce6b-4e8d-91d3-fa51975e13c4)

2024-02-27 11:14 UTC, oykuermann requested changes
I'll check after changes

2024-02-27 13:00 UTC, oykuermann approved these changes

2024-02-27 13:00 UTC, merged