Update docs for videocourses
abpframework/abp pull request #19223
Opened 2024-03-06 09:29 UTC by honurbu

Used In => https://github.com/volosoft/vs-internal/pull/3866

Video course link added to documentation (rel-8.0)

2024-03-06 09:29 UTC, salihozkara approved these changes

2024-03-06 13:50 UTC, oykuermann requested changes
Waiting for: https://github.com/volosoft/vs-internal/pull/3866#pullrequestreview-1919815748

2024-03-08 12:34 UTC, oykuermann commented
![image](https://github.com/abpframework/abp/assets/142304401/bb805751-f47e-4f25-b6de-d24b4349c2dc)

- [x] There is two part-1.

Blazor&Angular Authorization page doesn't have video link:
- [x]  /latest/UI/Blazor/Authorization
- [x]  /latest/UI/Blazor/Authorization
![image](https://github.com/abpframework/abp/assets/142304401/59889e96-21ea-4778-828d-23735ed8ba14)

- [x] /latest/UI/Angular/Localization

- [x] /latest/UI/AspNetCore/JavaScript-API/Localization

- [x] /latest/UI/Angular/Localization

pages do not have localization links.
![image](https://github.com/abpframework/abp/assets/142304401/c8d52571-af74-423a-9abb-5b6a1d62d151)

2024-03-11 08:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/abpframework/abp?pullRequest=19223) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/abpframework/abp?pullRequest=19223) before we can accept your contribution.<br/>**9** out of **11** committers have signed the CLA.<br/><br/>:white_check_mark: denizdemirkan<br/>:white_check_mark: maliming<br/>:white_check_mark: honurbu<br/>:white_check_mark: salihozkara<br/>:white_check_mark: EngincanV<br/>:white_check_mark: ahmetfarukulu<br/>:white_check_mark: enisn<br/>:white_check_mark: realLiangshiwei<br/>:white_check_mark: gizemmutukurt<br/>:x: sumeyyeKurtulus<br/>:x: oykuermann<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/abpframework/abp?pullRequest=19223) it.</sub>

2024-03-11 08:17 UTC, EngincanV commented
![image](https://github.com/abpframework/abp/assets/43685404/5920bfa9-ba77-4e3a-9a00-1d20af5693b4)

Since this PR will be merged to rel-8.0, you should not merge it with the dev branch. So, please revert the merge commit and make a hard reset. @honurbu

2024-03-11 12:05 UTC, oykuermann approved these changes

2024-03-11 12:05 UTC, merged