Update Turkish localization
abpframework/abp pull request #19282
Opened 2024-03-13 09:12 UTC by honurbu

Used In => https://github.com/volosoft/vs-internal/pull/3927

2024-03-13 10:08 UTC, salihozkara approved these changes

2024-03-13 11:02 UTC, enisn approved these changes

2024-03-13 11:54 UTC, oykuermann requested changes
I'll check after changes

2024-03-14 09:08 UTC, salihozkara commented on abp_io/AbpIoLocalization/AbpIoLocalization/Commercial/Localization/Resources/fi.json
> +    "RegisterDemo": "Rekisteröidy"
```suggestion
    "ExtendNow": "Laajenna / Uusi",
    "RegisterDemo": "Rekisteröidy"
```

2024-03-19 14:32 UTC, oykuermann approved these changes

2024-03-19 14:33 UTC, merged