Adding toaster notifications with new "SuccessfullySaved" localization
abpframework/abp pull request #19326
Opened 2024-03-15 13:48 UTC by yusuf-cirak

### Description

Resolves #19324

- Adding localization messages.
- Adding toast messages to feature management, identity, tenant-management.

### Checklist

- [x] I fully tested it as developer

### How to test it?

- Perform some create or update operations.

2024-03-15 13:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/abpframework/abp?pullRequest=19326) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/abpframework/abp?pullRequest=19326) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/abpframework/abp?pullRequest=19326) it.</sub>

2024-03-15 20:09 UTC, masumulu28 approved these changes

2024-03-18 11:08 UTC, oykuermann requested changes
Localization names should be 'SavedSuccesfully' and 'DeletedSuccesfully'. Please, rewrite all the localizations.
![image](https://github.com/abpframework/abp/assets/142304401/c8791f4f-69ab-4323-9a0b-80c86c9da109)

2024-03-19 06:12 UTC, yusuf-cirak commented
> Localization names should be 'SavedSuccesfully' and 'DeletedSuccesfully'. Please, rewrite all the localizations. ![image](https://private-user-images.githubusercontent.com/142304401/313651932-c8791f4f-69ab-4323-9a0b-80c86c9da109.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mjg5NDUsIm5iZiI6MTcxMDgyODY0NSwicGF0aCI6Ii8xNDIzMDQ0MDEvMzEzNjUxOTMyLWM4NzkxZjRmLTY5YWItNDMyMy05YTBiLTgwYzg2YzlkYTEwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwNjEwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDdiZjBhMmJmYzllOTI1NjdmOTNkNjMwZTQzYWJiNzI3NzllZmMwNzM3Y2U3ZDE0MWNkZWFhN2ZlY2FlM2RiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pv7NuhU_KXxJqpGj1qkQ61X-vV0gwnsa3i0YhfsJImU)

I'm not sure about this. Other UI's will need to change their localizations too. If that's okay, i can change all.

2024-03-19 06:15 UTC, gizemmutukurt commented
This is how the majority approved it on the channel @yusuf-cirak 

![image](https://github.com/abpframework/abp/assets/99716457/1c8fee1d-cc6e-4010-b354-6eb48bbd143c)

2024-03-22 00:18 UTC, masumulu28 approved these changes

2024-03-22 00:18 UTC, masum-ulu commented on npm/ng-packs/packages/permission-management/src/lib/components/permission-management.component.ts
> +    private readonly toasterService: ToasterService,
Mark as `protected`

2024-03-26 12:11 UTC, oykuermann approved these changes

2024-03-26 12:11 UTC, merged