CLI: Add angular implementation after new microservice added to project
abpframework/abp pull request #19381
Opened 2024-03-22 00:58 UTC by masumulu28

### Description

This PR provides to adding new angular library after new microservice-service-pro created to project and **if project uses angular ui**

### Checklist

- [ ] I fully tested it as developer / designer and created unit / integration tests
- [ ] I documented it (or no need to document or I will create a separate documentation issue)

### How to test it?
`Not done yet`

2024-03-25 22:45 UTC, masumulu28 commented on framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Commands/ProjectCreationCommandBase.cs
> +        commandBuilder.Append($" --override {(isOverride ? "true" : "false")} ");
Normally I could add `if` statements yet, we have to set `true` or `false` to schematic argument it is required, this command hasn't default values

2024-03-26 05:26 UTC, yekalkan approved these changes

2024-03-26 06:23 UTC, EngincanV approved these changes

2024-03-27 06:28 UTC, gizemmutukurt reviewed
Can you give information about the test?

2024-03-27 12:58 UTC, gizemmutukurt requested changes
When navigation is added, an error is received.

2024-03-27 14:01 UTC, gizemmutukurt approved these changes

2024-03-27 14:03 UTC, merged