Angular - Account Pages Sidebar Flicker on Reload
abpframework/abp pull request #19413
Opened 2024-03-25 12:51 UTC by sumeyyeKurtulus

### Description

Resolves #19038 and relates #17061.
As another issue was fixed by #17061, the code piece added inside the `ngOnInit` lifecycle hook breaks the account pages and results in a flicker on reload. That is why, we have commented out the related part to propose a solution.

[SidebarFlickerResolved.webm](https://github.com/abpframework/abp/assets/92928815/59d95d8f-5c43-46b9-9b7d-683e78883c05)

### Checklist

- [X] I fully tested it as developer

### How to test it?

You can test it by following the instructions as declared in the issue.

2024-03-25 12:57 UTC, masumulu28 commented on npm/ng-packs/apps/dev-app/src/app/home/home.component.ts
> +  private authService = inject(AuthService);
mark as `protected readonly`

2024-03-25 12:58 UTC, masumulu28 commented on npm/ng-packs/packages/core/src/lib/components/dynamic-layout.component.ts
> +  private routerEvents = inject(RouterEvents);
Make them private to `protected readonly`

2024-03-25 12:59 UTC, masumulu28 commented on npm/ng-packs/packages/core/src/lib/components/dynamic-layout.component.ts
> +    // this.getLayout();
Remove NgOninit

2024-03-25 13:00 UTC, masum-ulu commented on npm/ng-packs/packages/theme-basic/src/lib/components/application-layout/application-layout.component.ts
> +  public service = inject(LayoutService);
Mark as `public readonly`

2024-03-26 10:17 UTC, masum-ulu approved these changes

2024-03-27 14:34 UTC, oykuermann requested changes
After implementing AuthGuard and login, a blank page opened:
![image](https://github.com/abpframework/abp/assets/142304401/420716b5-56a4-4eb7-9509-2bad86f4eedf)
![image](https://github.com/abpframework/abp/assets/142304401/50667d09-d3f5-459f-a4db-d793c1ea23cb)

2024-03-28 03:39 UTC, sumeyyeKurtulus commented
Hello again @oykuermann I have added a new condition to render the layout and manage the issue mentioned above #17061
fyi @masumulu28

2024-03-28 13:25 UTC, masum-ulu approved these changes

2024-03-29 09:18 UTC, oykuermann approved these changes

2024-03-29 09:33 UTC, merged