Docs Module Improvements and Add Single Project Mode
abpframework/abp pull request #19419
Opened 2024-03-26 09:16 UTC by salihozkara

### Description

Resolves #xxxx (write the related issue number if available)

TODO: Describe what this PR has changed, add screenshot or animated GIF if available, write if it is a breaking change, and how to fix the breaking changes for existing applications if so.

### Checklist

- [ ] I fully tested it as developer / designer and created unit / integration tests
- [ ] I documented it (or no need to document or I will create a separate documentation issue)

### How to test it?

Please describe how this can be tested by the test engineers if it is not already explicit - or remove this section if no need to description.

2024-07-04 13:01 UTC, EngincanV approved these changes

2024-07-04 13:02 UTC, EngincanV commented
@gizemmutukurt Can you please test the docs module against **multi project mode** and **single project mode**, please? You can write to me or @salihozkara, for test steps.

2024-07-04 13:58 UTC, gizemmutukurt commented
With these configurations, I get a 404 error on startup.
![image](https://github.com/abpframework/abp/assets/99716457/9784f402-adaa-4ad1-a783-b66f9c5689c4)
![image](https://github.com/abpframework/abp/assets/99716457/d682964b-70a3-477d-8d16-24491f223516)

2024-07-04 13:58 UTC, gizemmutukurt requested changes
- [ ] With these configurations, I get a 404 error on startup.

![image](https://github.com/abpframework/abp/assets/99716457/9784f402-adaa-4ad1-a783-b66f9c5689c4)
![image](https://github.com/abpframework/abp/assets/99716457/d682964b-70a3-477d-8d16-24491f223516)

2024-07-05 08:21 UTC, gizemmutukurt approved these changes

2024-07-05 08:21 UTC, merged