Adding constants to theme-shared module for error messages by status code
abpframework/abp pull request #19421
Opened 2024-03-26 13:07 UTC by yusuf-cirak

### Description

Resolves #19416

- Adding constant to reduce switch-case based code and improve code quality.
- Refactoring `http-error-wrapper` component with the latest features of Angular 17.1
- Formatting the current code with Prettier

### Checklist

- [x] I fully tested it as developer

### How to test it?
- Go to `http://localhost:4200/error?status=404` or `http://localhost:4200/error`. If an error component is rendered, there is no issue.

2024-03-26 14:13 UTC, masumulu28 approved these changes

2024-03-28 07:00 UTC, oykuermann requested changes
Waiting for https://github.com/volosoft/lepton/pull/2155#pullrequestreview-1963117191

2024-03-28 11:37 UTC, masumulu28 commented on npm/ng-packs/packages/theme-shared/src/lib/components/http-error-wrapper/http-error-wrapper.component.ts
> +  }
It seems like you create this method what where did you use ?

2024-03-28 13:15 UTC, oykuermann approved these changes

2024-03-28 13:16 UTC, merged