Add `AbpAuthenticationSessionState` to logout from other tabs
abpframework/abp pull request #19563
Opened 2024-04-17 08:04 UTC by realLiangshiwei

### Description

Related: https://github.com/abpframework/abp/issues/19488

### Checklist

- [x] I fully tested it as developer / designer and created unit / integration tests
- [x] I documented it (or no need to document or I will create a separate documentation issue)

### How to test it?

Run the template

2024-04-18 11:00 UTC, enisn approved these changes

2024-04-18 11:34 UTC, oykuermann requested changes
Blazor Server - Home page & My Account pages did not log out.
 
[18.04.2024 14_15.webm](https://github.com/abpframework/abp/assets/142304401/a513e58a-b2b1-4ba2-b5f0-8b7bcbd3fc64)

Blazor Wasm - My Account page cannot be opened.
![image](https://github.com/abpframework/abp/assets/142304401/11aa84a7-e387-48bd-adf5-656c7615d312)

Blazor Wasm - When you log out from any page except 'Home page', you are redirected to the home page on every tab.

2024-04-19 02:27 UTC, realLiangshiwei commented
This window is not logged in, so it does not need to be refreshed
<img width="805" alt="image" src="https://github.com/abpframework/abp/assets/16813853/a3f1a1ff-c796-4450-b32c-02bbba716c8c">

My Account page is MVC UI: https://github.com/abpframework/abp/pull/19569
You can ignore it here.

> Blazor Wasm - My Account page cannot be opened.

Fixed.

> Blazor Wasm - When you log out from any page except 'Home page', you are redirected to the home page on every tab.

I could not reproduce this.

2024-04-22 08:14 UTC, oykuermann requested changes
To reproduce the last one: 
1. Go to tenants page on app Blazor web assembly template.
2. Try to log out.
3. App will redirect you to home page

I reproduced again

2024-04-22 10:48 UTC, oykuermann approved these changes

2024-04-22 10:49 UTC, merged