Added using-blob-storage-with-abp article
abpframework/abp pull request #19733
Opened 2024-05-07 12:09 UTC by EmreKendirli

### Description

Resolves #xxxx (write the related issue number if available)

TODO: Describe what this PR has changed, add screenshot or animated GIF if available, write if it is a breaking change, and how to fix the breaking changes for existing applications if so.

### Checklist

- [ ] I fully tested it as developer / designer and created unit / integration tests
- [ ] I documented it (or no need to document or I will create a separate documentation issue)

### How to test it?

Please describe how this can be tested by the test engineers if it is not already explicit - or remove this section if no need to description.

2024-05-07 14:11 UTC, EngincanV requested changes
The article is good, it covers the topic with a plain example @EmreKendirli 👏 
You can consider my suggestions and apply them to the article. Then please "re-request review", so I can quickly take a look at it.

2024-05-07 14:11 UTC, EngincanV commented on docs/en/Community-Articles/2024-04-19-using-blob-storage-with-abp/post.md
> + ABP Framework is a comprehensive development framework for modern web applications and microservice architectures. This framework offers its users the possibility to quickly build scalable and modul
In this paragraph, you are only describing the ABP Framework but do not link the paragraph with the article. Therefore, I think you should first plainly describe the framework and then you should mention that ABP Framework provides Blob Storing infrastructure to easily integrate into your application and provides multiple pre-built providers.

So, I think you may update this paragraph as below:

```suggestion
 ABP Framework is a comprehensive development framework for modern web applications and microservice architectures. ABP Framework [provides an abstraction to work with BLOBs and provides some pre-built storage providers](https://docs.abp.io/en/abp/latest/Blob-Storing) that you can easily integrate into your application. In this article, I will show you how to store BLOBs in a relational or non-relational database by using the [Database Provider](https://docs.abp.io/en/abp/latest/Blob-Storing-Database).
```

You can update the paragraph with your sentences, but keep that in mind, adding links for further information is a good practice, so the readers can check the official document if they want to learn more.

2024-05-07 14:11 UTC, EngincanV commented on docs/en/Community-Articles/2024-04-19-using-blob-storage-with-abp/post.md
> +   ![Step 1](./images/step1.png)
If you are showing a code-block to the readers, they should be able to directly copy-paste the code-blocks and try it instantly within their applications. Therefore, showing the code in the code-blocks in markdown is a good practise. Thus, please update this and all images with the relevant code-blocks. (Also, you can use : before the previous sentence of the code-block):

````suggestion
The first step is to define a Blob Container for storing profile pictures. The Blob Container represents the storage space that will be used to store the profile pictures:

```csharp
public class ProfilePictureContainer : IBlobContainer
{
    public string Name => "profile-pictures";
}
```

````

Please also update other images that contain code-blocks.

---

Also, you may mention that the `BlobContainerNameAttribute` can be used to set the container name (https://docs.abp.io/en/abp/latest/Blob-Storing#typed-iblobcontainer)

2024-05-07 14:11 UTC, EngincanV commented on docs/en/Community-Articles/2024-04-19-using-blob-storage-with-abp/post.md
> +Create the ProfileAppService class and derive it from the ApplicationService class. This class will perform the necessary operations to store and retrieve profile pictures.
For the class, property, and method names, you can use the (`) character:

```suggestion
Create the `ProfileAppService` class and derive it from the `ApplicationService` class. This class will perform the necessary operations to store and retrieve profile pictures.
```

Please wrap the special names (code-related) with ` character. Like in the example above.

2024-05-07 14:11 UTC, EngincanV commented on docs/en/Community-Articles/2024-04-19-using-blob-storage-with-abp/post.md
> +- #### Step 1: Blob Container Identification
```suggestion
- #### Step 1: Configure the Blob Container
```

This might be a better title for this section.

2024-05-07 14:11 UTC, EngincanV commented on docs/en/Community-Articles/2024-04-19-using-blob-storage-with-abp/post.md
> +- #### Step 2: Create ProfileAppService
```suggestion
- #### Step 2: Create the ProfileAppService (Saving & Reading BLOBs)
```

This might be a better title for this section, but it can stay as it is, it's totally up to you.

2024-05-07 14:11 UTC, EngincanV commented on docs/en/Community-Articles/2024-04-19-using-blob-storage-with-abp/post.md
> +- #### Step 3: Blob Container Connection
```suggestion
- #### Step 3: Inject the `IBlobContainer` Service
```

This might be a better title for this section, "Blob Container Connection" can be misleading as a title for the section.

2024-05-07 14:11 UTC, EngincanV commented on docs/en/Community-Articles/2024-04-19-using-blob-storage-with-abp/post.md
> +In the constructor method, inject the dependency into the IBlobContainer interface. This interface is used to interact with the Blob Container.
> "In the constructor method, inject the dependency into the IBlobContainer interface." 

It occurred to me that this sentence is not right (not in the correct form) and I think you can update it as below:

```suggestion
Inject the `IBlobContainer` service, in the constructor of the `ProfileAppService` class. The `IBlobContainer` is the main interface to store and read BLOB and is used to interact with the container.
```

2024-05-07 14:11 UTC, EngincanV commented on docs/en/Community-Articles/2024-04-19-using-blob-storage-with-abp/post.md
> +## What are the advantages/disadvantages of keeping in Blob Storage database?
```suggestion
## What are the Advantages/Disadvantages of Keeping the BLOBs in a Database? 
```

2024-05-07 14:11 UTC, EngincanV commented on docs/en/Community-Articles/2024-04-19-using-blob-storage-with-abp/post.md
> +## Information about Blob Storage entagrations
It's a [good practise to having a paragraph](https://developers.google.com/tech-writing/two/large-docs) after the title to pre-explain the section:

```suggestion
## Other Blob Storage Providers

ABP Framework provides some other [pre-built storage providers](https://docs.abp.io/en/abp/latest/Blob-Storing#blob-storage-providers) besides the [Database Provider](https://docs.abp.io/en/abp/latest/Blob-Storing-Database) shown in this article:
```

2024-05-08 07:53 UTC, EngincanV approved these changes

2024-05-09 08:41 UTC, hikalkan approved these changes

2024-05-09 08:41 UTC, merged