Remove Code markers from Razor file
abpframework/abp pull request #20252
Opened 2024-07-19 05:44 UTC by realLiangshiwei

### Description

Resolves https://github.com/volosoft/volo/issues/18066

### Checklist

- [x] I fully tested it as developer / designer and created unit / integration tests
- [x] I documented it (or no need to document or I will create a separate documentation issue)

### How to test it?

`abp new BlazorServer.EfCore -t app-pro -u blazor-server --mobile none --database-provider mongodb -csf --theme lepton --version 8.2.0`

2024-07-19 08:35 UTC, enisn approved these changes

2024-07-19 08:49 UTC, realLiangshiwei commented
@okyrylchuk 
you can ingore the CI test, Its error has nothing to do with this PR

2024-07-23 19:10 UTC, okyrylchuk commented
@realLiangshiwei I'll ignore 😆 

But I guess you meant @oykuermann 😉

2024-07-29 10:17 UTC, oykuermann requested changes
![image](https://github.com/user-attachments/assets/4e754e69-91a8-4183-8f08-164a01fb258d)
 I got an error when running the .Blazor project

2024-07-29 10:20 UTC, oykuermann approved these changes

2024-07-29 10:20 UTC, merged