Release post for v8.3.0
abpframework/abp pull request #20367
Opened 2024-08-01 09:35 UTC by EngincanV

### Description

Resolves https://github.com/volosoft/vs-internal/issues/4609

### Checklist

- [X] I fully tested it as developer / designer and created unit / integration tests
- [X] I documented it (or no need to document or I will create a separate documentation issue)

2024-08-01 11:14 UTC, hikalkan requested changes

2024-08-01 11:14 UTC, hikalkan commented on docs/en/Blog-Posts/2024-07-31 v8_3_Preview/post.md
> +Today, we are happy to release [ABP](abp.io) version **8.3 RC** (Release Candidate). This blog post introduces the new features and important changes in this new version.
```suggestion
Today, we are happy to release [ABP](https://abp.io) version **8.3 RC** (Release Candidate). This blog post introduces the new features and important changes in this new version.
```

2024-08-01 12:45 UTC, berkansasmaz approved these changes

2024-08-12 06:32 UTC, hikalkan approved these changes

2024-08-12 06:32 UTC, merged