Angular - Update Toastr Styles
abpframework/abp pull request #20494
Opened 2024-08-13 13:41 UTC by sumeyyeKurtulus

### Description

Resolves the latest toastr styles. Here is a demonstration sample

<img width="434" alt="image" src="https://github.com/user-attachments/assets/c1a93e4e-9ff9-45f5-90d7-cb5bdd5063d0">

### Checklist

- [X] I fully tested it as developer / designer and created unit / integration tests
- [X] I documented it (or no need to document or I will create a separate documentation issue)

2024-08-14 04:50 UTC, gizemmutukurt requested changes
We can improve the alignment between the icon and the text.

![image](https://github.com/user-attachments/assets/4b9c1005-47d8-4730-93b5-9cd2b41e7b39)

2024-08-19 05:19 UTC, masum-ulu approved these changes

2024-08-19 06:11 UTC, gizemmutukurt requested changes
The distance between icon and text should be shortened a little bit.
![image](https://github.com/user-attachments/assets/09c0cc45-001e-4cd6-91c9-183e5a205d53)

2024-08-19 06:34 UTC, gizemmutukurt approved these changes

2024-08-19 06:34 UTC, merged