new.abp.io page's title and descriptions updates
abpframework/abp pull request #20726
Opened 2024-09-04 00:15 UTC by dgnyldrm7

Related [4299](https://github.com/volosoft/vs-internal/pull/4660)

2024-09-12 06:45 UTC, salihozkara requested changes
Make sure that the key whose contents you are changing is not used elsewhere. Or create a new key

2024-09-12 06:45 UTC, salihozkara commented on abp_io/AbpIoLocalization/AbpIoLocalization/Base/Localization/Resources/en-GB.json
> +    "AbpConferenceDescription": "On 25, 26 September 2024, we’re hosting a free, live, virtual event where community speakers cover topics about .NET and soft-skills."
This is a generic key please create a new key or take the date as a variable

2024-09-12 06:45 UTC, salihozkara commented on abp_io/AbpIoLocalization/AbpIoLocalization/Base/Localization/Resources/en.json
> +    "AbpConferenceDescription": "On 25, 26 September 2024, we’re hosting a free, live, virtual event where community speakers cover topics about .NET and soft-skills.",
This is a generic key please create a new key or take the date as a variable

2024-09-12 06:45 UTC, salihozkara commented on abp_io/AbpIoLocalization/AbpIoLocalization/Www/Localization/Resources/en.json
> +    "GetStarted": "Get Started with ABP | Quick and Easy Setup Guide",
This is a generic key please create a new key

2024-09-13 06:42 UTC, salihozkara approved these changes

2024-09-13 13:04 UTC, oykuermann requested changes
Waiting for https://github.com/volosoft/vs-internal/pull/4660#issuecomment-2348666650

2024-09-25 07:33 UTC, salihozkara approved these changes

2024-09-25 08:25 UTC, oykuermann approved these changes

2024-09-25 08:39 UTC, merged