add localization.
abpframework/abp pull request #20964
Opened 2024-10-03 13:29 UTC by fahrigedik

Related https://github.com/volosoft/vs-internal/pull/5133

2024-10-03 18:30 UTC, salihozkara requested changes

2024-10-03 18:30 UTC, salihozkara commented on abp_io/AbpIoLocalization/AbpIoLocalization/Community/Localization/Resources/en.json
> +    "MemberMetaDescription" : "ABP Blog for .NET development, cross-platform, ASP.NET application templates, ABP-related news and more..."
```suggestion
    "BlogMemberMetaDescription" : "ABP Blog for .NET development, cross-platform, ASP.NET application templates, ABP-related news and more..."
```

2024-10-04 14:21 UTC, salihozkara approved these changes

2024-10-04 14:52 UTC, oykuermann reviewed
Waiting for https://github.com/volosoft/vs-internal/pull/5133#pullrequestreview-2348274950

2024-10-07 09:52 UTC, oykuermann approved these changes

2024-10-07 09:52 UTC, merged