Angular - Adding Search for the Permissions Modal
abpframework/abp pull request #21123
Opened 2024-10-18 13:40 UTC by sumeyyeKurtulus

### Description

Resolves #21109 

Here is a small demo for the changes

https://github.com/user-attachments/assets/c77116f8-62e7-471a-a426-109d076b8779

### Checklist

- [X] I fully tested it as developer / designer and created unit / integration tests
- [X] I documented it (or no need to document or I will create a separate documentation issue)

### How to test it?

-You can directly copy the changes to templates and navigate between the permission modals.

2024-10-21 08:51 UTC, masum-ulu requested changes
Use signal & computed and search localized displayName

2024-10-21 13:52 UTC, sumeyyeKurtulus commented
> Use signal & computed and search localized displayName

I have added the signal implementation. However, I did not modify the localized displayName since it is already registered in this way. We should either use the `name` prop by localizing manually, or `displayName` directly.

2024-10-22 06:22 UTC, masum-ulu approved these changes

2024-10-22 07:49 UTC, oykuermann requested changes
- [x] After a search with no result, this section should not appear:

![image](https://github.com/user-attachments/assets/be8f8ab6-92a0-46b3-870e-69edaaa8b387)


- [x] After search, we can display the first item's permissions:

![image](https://github.com/user-attachments/assets/31281897-ab06-49b3-a055-60dc421af79f)

[screencast-localhost_4200-2024_10_22-10_43_06.webm](https://github.com/user-attachments/assets/3297ebd7-6376-4705-a180-ebe1d9b960b0)

- [x] After searching smt, close the modal and reopen. Filter is not clear:

[screencast-localhost_4200-2024_10_22-10_43_06.webm](https://github.com/user-attachments/assets/8569bcb1-5f15-499f-8ebb-2f300223ade1)

- [x] After filtering & pressing 'Grant all permissions', I expect to see only filtering items to be selected.

[screencast-localhost_4200-2024_10_22-10_47_26.webm](https://github.com/user-attachments/assets/94595dab-ac83-42b4-b399-f8d2597cab24)

2024-10-22 11:03 UTC, closed without merging