Angular - Search Configurations for the Permissions Modal
abpframework/abp pull request #21184
Opened 2024-10-24 12:22 UTC by sumeyyeKurtulus

### Description

Resolves #21109 && relates [this closed PR](https://github.com/abpframework/abp/pull/21123).

2024-10-28 08:16 UTC, masum-ulu approved these changes

2024-10-28 09:50 UTC, oykuermann requested changes
Angular - After filtering & granting all permission, the Select All button seems to be selected on all pages.

[screencast-localhost_4200-2024_10_28-12_48_03.webm](https://github.com/user-attachments/assets/643fddc9-62da-4a6d-8245-21409c80b284)

2024-10-30 05:34 UTC, sumeyyeKurtulus commented
> Angular - After filtering & granting all permission, the Select All button seems to be selected on all pages.
> 
>  screencast-localhost_4200-2024_10_28-12_48_03.webm

However, it has the same behavior in the previous version, and I believe this is the one that makes sense.


https://github.com/user-attachments/assets/739938dd-18a7-4bf9-9ca7-6ae524bcd001

2024-10-30 07:18 UTC, oykuermann commented
I'll create another issue for it.

2024-10-30 07:18 UTC, oykuermann approved these changes

2024-10-30 07:34 UTC, merged