Docs Content Reviews - Issue 4531 2
abpframework/abp pull request #21220
Opened 2024-10-31 13:00 UTC by fahrigedik

Related : https://github.com/volosoft/vs-internal/issues/4531

2024-10-31 13:00 UTC, gizemmutukurt approved these changes

2024-11-04 05:09 UTC, gizemmutukurt requested changes
getting an error during operation.

`#8 164.4 /app/volo/abp/identity-pro/src/Volo.Abp.Identity.Pro.Domain/Volo/Abp/Identity/Session/IdentitySessionDynamicClaimsPrincipalContributor.cs(7,27): error CS0234: The type or namespace name 'Authentication' does not exist in the namespace 'Volo.Abp.AspNetCore' (are you missing an assembly reference?) [/app/volo/abp/identity-pro/src/Volo.Abp.Identity.Pro.Domain/Volo.Abp.Identity.Pro.Domain.csproj]`

2024-11-06 08:38 UTC, gizemmutukurt approved these changes
@oykuermann also set up the appropriate environment for this. That's why he will test it.

2024-11-06 11:19 UTC, oykuermann approved these changes

2024-11-06 11:19 UTC, merged