Lazy expandable feature for documentation
abpframework/abp pull request #21689
Opened 2024-12-20 03:44 UTC by realLiangshiwei

### Description

Resolves https://github.com/abpframework/abp/issues/21095

### Checklist

- [x] I fully tested it as developer / designer and created unit / integration tests
- [x] I documented it (or no need to document or I will create a separate documentation issue)

### How to test it?

Run the `VoloDocs.Web` app

2024-12-23 07:42 UTC, salihozkara requested changes
Can you create the url with Url.Page instead of creating it from js? We may have changed the routing in Asp Net Core.

2024-12-23 07:42 UTC, salihozkara commented on modules/docs/src/Volo.Docs.Web/Pages/Documents/Project/index.js
> +                        path += "/" + doc.project.name
```suggestion
                        path += "/" + doc.project.shortName
```

2024-12-23 07:42 UTC, salihozkara commented on modules/docs/src/Volo.Docs.Web/Pages/Documents/Project/Index.cshtml
> +                    name: '@Model.Project.Name',
```suggestion
                    shortName: '@Model.Project.ShortName',
```

2024-12-23 12:08 UTC, realLiangshiwei commented
@salihozkara  okay , I added a new `DocumentNavigationController` to generate links.

2024-12-23 14:16 UTC, oykuermann requested changes
Items should be rendered if the main page is open.
<img width="609" alt="image" src="https://github.com/user-attachments/assets/a85f3a4d-e583-4335-99a6-3e1efefcb13c" />
![image](https://github.com/user-attachments/assets/04a0e110-1ee8-44d1-b4dc-104077559eb0)

2024-12-25 10:57 UTC, salihozkara approved these changes

2024-12-25 11:46 UTC, oykuermann commented
> Items should be rendered if the main page is open. <img alt="image" width="609" src="https://private-user-images.githubusercontent.com/142304401/398176817-a85f3a4d-e583-4335-99a6-3e1efefcb13c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjc0NDIsIm5iZiI6MTczNTEyNzE0MiwicGF0aCI6Ii8xNDIzMDQ0MDEvMzk4MTc2ODE3LWE4NWYzYTRkLWU1ODMtNDMzNS05OWE2LTNlMWVmZWZjYjEzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxMTQ1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzVkNmFlZmQ0OTI1ZTkzMjI1M2NmNzcwYTdkYzc2MmJlM2Q0MGQwZmM5OGIzMTQ1MmE4YWMyYzBkMGY0MTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ada2knvJ014ghlRwO0z0m3O1JriW7n3qgnxGt_QVvzo"> ![image](https://private-user-images.githubusercontent.com/142304401/398181266-04a0e110-1ee8-44d1-b4dc-104077559eb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjc0NDIsIm5iZiI6MTczNTEyNzE0MiwicGF0aCI6Ii8xNDIzMDQ0MDEvMzk4MTgxMjY2LTA0YTBlMTEwLTFlZTgtNDRkMS1iNGRjLTEwNDA3NzU1OWViMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxMTQ1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDA5YzNmNmQzM2M3NDQ0ZTU0NGJiNjQ4MTFjZjNlNWM0MGEzNTQxNzI5ZDg3ZjY1MTQ2ZWM3NTliZjZiYjgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D407CiMe6aFhOBAqVI1jtagkOIKq1i_kpYVsXQgOMck)

This problem still not resolved:
<img width="1144" alt="image" src="https://github.com/user-attachments/assets/c3302706-3d9a-4b8c-97e2-0cbd477d2871" />

2024-12-25 11:47 UTC, oykuermann requested changes
I'll check after changes.

2024-12-25 13:40 UTC, oykuermann approved these changes

2024-12-25 13:40 UTC, merged