Add a md file for Environment (Angular)
abpframework/abp pull request #5139
Opened 2020-08-21 09:17 UTC by bnymncoskuner

Resolves #4991

2020-08-21 12:43 UTC, hikalkan commented
I assigned to 3.1. Right?

2020-08-21 13:31 UTC, mehmet-erim commented on docs/en/UI/Angular/Environment.md
> +Every application needs some ** environment ** variables. In Angular world, this is usually managed by `environment.ts`, `environment.prod.ts` and so on. It is the same for Abp as well.
```suggestion
Every application needs some ** environment ** variables. In Angular world, this is usually managed by `environment.ts`, `environment.prod.ts` and so on. It is the same for ABP as well. 
```

2020-08-21 13:34 UTC, mehmet-erim commented on docs/en/UI/Angular/Environment.md
> +}
```suggestion
export interface Environment {
  apis: Apis;
  application: Application;
  oAuthConfig: AuthConfig;
  production: boolean;
  remoteEnv?: RemoteEnv;
}
```

`hmr` and `localization` properties will probably be removed from the type.

2020-08-21 13:39 UTC, mehmet-erim commented on docs/en/UI/Angular/Environment.md
> +You can read about `Localization` [here in detail](./Localization.md)
```suggestion
```

For the reason I explained above, this title should never exist.

2020-08-25 15:45 UTC, armanozak requested changes

2020-08-25 15:45 UTC, armanozak commented on docs/en/UI/Angular/Multi-Tenancy.md
> +<h2 id="domain-tenant-resolver">Domain Tenant Resolver</h2>
```suggestion
## Domain Tenant Resolver
```

2020-08-25 15:46 UTC, armanozak approved these changes

2020-08-25 15:46 UTC, merged