Add ICurrentImpersonatorUser & ICurrentImpersonatorTenant.
abpframework/abp pull request #5190
Opened 2020-08-27 06:10 UTC by maliming

2020-09-07 12:33 UTC, hikalkan requested changes

2020-09-07 12:33 UTC, hikalkan commented on modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityLinkUser.cs
> +    {
Create a protected default constructor, for orm deserialization.

2020-09-07 12:33 UTC, hikalkan commented on modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityLinkUser.cs
> +        public virtual Guid SourceUserId { get; protected set; }
We write properties on top of the constructor, by convention.

2020-09-07 12:33 UTC, hikalkan commented on modules/identity/src/Volo.Abp.Identity.EntityFrameworkCore/Volo/Abp/Identity/EntityFrameworkCore/IIdentityDbContext.cs
> +        DbSet<IdentityLinkUser> IdentityLinkUsers { get; set; }
`LinkUsers` would be enough for the property name. Same for `SecurityLogs` too (take Users, Roles.. as examples)

2020-09-07 12:33 UTC, hikalkan commented on framework/src/Volo.Abp.MultiTenancy/Volo/Abp/MultiTenancy/CurrentImpersonatorTenant.cs
> +    public class CurrentImpersonatorTenant : ICurrentImpersonatorTenant, ITransientDependency
Instead of introducing `ICurrentImpersonatorTenant`, just add a `ImpersonatorId` to the `ICurrentTenant`.

2020-09-07 12:33 UTC, hikalkan commented on framework/src/Volo.Abp.Security/Volo/Abp/Users/CurrentImpersonatorUser.cs
> +    public class CurrentImpersonatorUser : ICurrentImpersonatorUser, ITransientDependency
Instead, add `ImpersonatorId` to the `ICurrentUser`.

2020-09-08 11:44 UTC, olicooper commented
Couple of questions on this feature...
* Will there be a security log when someone starts and ends an impersonation session?
* Will tenants be able to allow/deny permission to impersonate? The use case for this is when a host 'support' user needs to provide support for a tenant. A tenant administrator can temporarily grant permission to access their data, then the user impersonates the tenant (not necessarily the user - so all updated records have the host UserId as the LastModifierId) to see all the information for the tenant. My current implementation involves checking a 'SupportAccessGranted' setting for each tenant on each API request.

2020-09-11 11:02 UTC, leonkosak commented
@hikalkan, @maliming 
I completely agree with second suggestion from @olicooper.
The default behavior should be that login as impersonator is not allowed. User should explicitly allow impersonation for defined period of time (for instance "to" datetime).
Of course, there could be option for "unlimited impersonator access".

I have use case that tenant stored in tenants are really sensitive and impersonator should not just login as one user (like in ANZ).
Of course, that is possible to view such accesses in AuditLogs table, but it should be prevented (rather than reacting when data are stolen).

My suggestions

1) **On tenant-level**, there should be setting "Allow automatic impersonation" which have the following options in dropdown menu:
- Allow on demand (**default** selected)
- Do not allow
- Allow always

**Allow on demand**
Tenant user have options (on topbar or somewhere in user settings - profile) for impersonalization:

- Do not allow (default, it goes back to this option when impersonalization allowed time ends)

- Allow limited (when user choose this option, there has to be option for how long or "to datetime" and has to be set)

- Allow always (mark as red or dangerous)


**Do not allow**
Tenant user has no option to set up personalization, because it is **forbidden** on tenant-level.

**Allow always**
Tenant user has no option to set up personalization, because it is **fully-allowed** on tenant-level.


I know that this is complicated logic, but it is required when there are really sensitive date (and GDPR-related data) and one user wants help from other user (for instance helpdesk which is not even the same company).

2020-09-14 13:59 UTC, maliming commented
Add `LinkLoginExtensionGrantValidator` to regenerate identity server token for re-signin(Angular).

![image](https://user-images.githubusercontent.com/6908465/93095237-720ad180-f6d5-11ea-92e4-bb7603f848dd.png)

2020-09-14 14:02 UTC, maliming commented
hi @olicooper @leonkosak 
I have encountered some problems with impersonating users/tenants, so I implement `link user` first, then I will open another PR. Your comments are welcome.

2020-09-14 17:22 UTC, olicooper commented
Thanks for your hard work @maliming, I will try this in my app to see if it works once it is on the nightly train.

One feature of my temporary solution ([seen here](https://github.com/abpframework/abp/issues/1082#issuecomment-574224409)) is the ability to limit what the support user can do via the permissions system. It was an accidental feature but it turned in to something quite interesting. 
* I created a static 'support' role on the host with a single 'View Tenants' permission and added a 'impersonate tenant' button to store the __tenantId in session cache and send with every request. This stops 'support' employees messing with the host or doing anything damaging.
* I created a static 'support' role in the migration seeding code which grants most permissions to the support role for each tenant.
* When a support user impersonates a tenant, they inherit the permissions of the tenant they are impersonating

This worked out great and allows each tenant to have fine-grained control over what a support person can do. It might be worth considering as an extension to this feature?

2020-09-16 11:04 UTC, ismcagdas approved these changes

2020-10-06 17:35 UTC, merged

2021-04-08 12:37 UTC, tvddev commented
Does anyone know if the impersonating a tenant user from the host side workaround that @olicooper has suggested above and in #1082 work in v4.3?