Add appsettings to enable/disable Redis as distributed cache
abpframework/abp pull request #5694
Opened 2020-10-03 09:54 UTC by RachaneeSaeng

To allow switching between In-Memory and Redis as a distributed cache.
Background: sometimes we want to stop using Redis (on production) for some reason while don't want to rebuilt and redeploy the app.

2020-10-06 14:31 UTC, hikalkan requested changes
Thank you for your contribution. However, this is an unnecessary **breaking change** with the current implementation. `IsEnabled` option should be optional and considered `true` by default for backward compability.

2020-10-07 05:20 UTC, rachanee-mwp commented
@hikalkan I have updated code to allow the setting `Redis:IsEnabled` to be optional and consider `true` of it is not set.
However, there is the `Code scanning results / CodeQL` was failed with some irrelevant errors.
Could you please review?

2020-10-08 08:25 UTC, hikalkan commented
Thanks for the changes.

I believe we should only make the changes in the AbpCachingStackExchangeRedisModule.cs and revert all the other changes (except the documentation).

Because these changes (adding Redis:IsEnabled as false to appsettings.json) changes the behaviour. Using redis in a distributed environment is essential and this change makes it easy to forget it as disabled. Previos code was disabling in only for development environment.

If you need to disable redis, you should do it in your own application. We don't want to add this to the startup templates.

Thanks for your contribution.

2020-10-08 10:51 UTC, rachanee-mwp commented
@hikalkan I've reverted changes from other files except the `AbpCachingStackExchangeRedisModule` and the documentation.
Could you please review?

2020-10-10 11:16 UTC, hikalkan commented
Great! Thanks :)

2020-10-10 11:16 UTC, merged

2023-03-16 06:19 UTC, ahmadalmunajjed commented
I think in the documentation of Redis-Cache it still mentions IsEnabled param even though it's no implemented anymore. So I suggest removing it from the documentation.