Spanish localization update for v3.2
abpframework/abp pull request #5720
Opened 2020-10-06 17:54 UTC by LuisPignataro

I have updated the localization files in Spanish with the changes that were made in English for version 3.2

2020-10-06 18:21 UTC, hikalkan requested changes

2020-10-06 18:21 UTC, hikalkan commented on framework/src/Volo.Abp.Ddd.Application.Contracts/Volo.Abp.Ddd.Application.Contracts.csproj
> +  <ItemGroup>
Please remove this ItemGroup (it is probably auto added by the VS).

2020-10-06 18:21 UTC, hikalkan commented on framework/src/Volo.Abp.Timing/Volo.Abp.Timing.csproj
> +  <ItemGroup>
Please remove this ItemGroup (it is probably auto added by the VS).

2020-10-06 18:21 UTC, hikalkan commented on framework/test/Volo.Abp.AspNetCore.Mvc.Tests/Volo.Abp.AspNetCore.Mvc.Tests.csproj
> +  <ItemGroup>
Please remove this ItemGroup (it is probably auto added by the VS).

2020-10-06 18:21 UTC, hikalkan commented
Thanks a lot. I have a few small change requests.

2020-10-09 15:03 UTC, LuisPignataro commented
Ready, clean up the projects!

2020-10-10 11:24 UTC, hikalkan commented
Thanks :)

2020-10-10 11:25 UTC, merged