Modify AbpNoContentActionFilter
abpframework/abp pull request #6108
Opened 2020-11-07 16:55 UTC by ilonze

Hi!
The AbpNoContentActionFilter shouldn't modify StatusCode to NoContent when action result has value, because may be result modify by custum result filter.

2020-11-08 11:11 UTC, maliming commented
Hi

Could you add a unit test for this change?

2020-11-08 11:11 UTC, maliming approved these changes

2020-11-09 04:55 UTC, maliming requested changes
Your PR contains some irrelevant changes

2020-11-09 09:16 UTC, closed without merging

2020-11-09 09:16 UTC, ilonze commented
Re-request