Cms-Kit page system implementation
abpframework/abp pull request #6996
Opened 2021-01-04 11:21 UTC by cotur

Closes: #6847

2021-01-05 14:05 UTC, enisn approved these changes

2021-01-06 10:54 UTC, ilkayilknur requested changes

2021-01-06 10:54 UTC, ilkayilknur commented on modules/cms-kit/src/Volo.CmsKit.Admin.HttpApi/Volo/CmsKit/Admin/Pages/PageAdminController.cs
> +        [Route("exists/{url}")]
We should use HTTP Head to check the existence of the URL. This implementation feels like an RPC. We should do it like HTTP Head `api/cms-kit-admin/pages\{url}`

2021-01-06 10:54 UTC, ilkayilknur commented on modules/cms-kit/test/Volo.CmsKit.Application.Tests/Pages/PageAdminAppService_Tests.cs
> +            await Should.ThrowAsync<Exception>(async () => await _pageAdminAppService.CreateAsync(dto));
We should create a spesific business exception here. What kind of exception does this call throw?

2021-01-12 11:27 UTC, ilkayilknur requested changes
I think we can also remove the `Description` properties from everywhere after our last meeting. Rest LGTM.

2021-01-12 11:27 UTC, ilkayilknur commented on modules/cms-kit/src/Volo.CmsKit.Domain.Shared/Volo/CmsKit/Localization/Resources/en.json
> +    "CmsKit:Page:0001": "The given url ({0}) is already exist."
The given url ({0}) already exists.

2021-01-12 11:27 UTC, ilkayilknur commented on modules/cms-kit/src/Volo.CmsKit.MongoDB/Volo/CmsKit/MongoDB/Pages/MongoPageRepository.cs
> +            return await (await GetMongoQueryableAsync(GetCancellationToken(cancellationToken)))
We can call `GetCancellationToken(cancellationToken)` once use returning value everywhere.

2021-01-12 11:27 UTC, ilkayilknur commented on modules/cms-kit/src/Volo.CmsKit.MongoDB/Volo/CmsKit/MongoDB/Pages/MongoPageRepository.cs
> +                .ToListAsync(GetCancellationToken(cancellationToken));
Please see my previous comment.

2021-01-13 12:49 UTC, ilkayilknur approved these changes

2021-01-13 12:49 UTC, merged