Added Routing to Cms-Kit Page
abpframework/abp pull request #7335
Opened 2021-01-19 08:53 UTC by cotur

2021-01-19 08:53 UTC, enisn approved these changes

2021-01-19 09:18 UTC, enisn approved these changes

2021-01-19 10:52 UTC, enisn approved these changes

2021-01-19 15:55 UTC, ilkayilknur requested changes
Getting 500 while accessing the page.

![image](https://user-images.githubusercontent.com/5785927/105058976-d96fce00-5a87-11eb-84ac-4471cd1b6679.png)

2021-01-20 11:38 UTC, enisn approved these changes

2021-01-20 11:44 UTC, ilkayilknur approved these changes

2021-01-20 11:44 UTC, merged