Cms Kit - Pages Prefix
abpframework/abp pull request #7731
Opened 2021-02-15 12:25 UTC by enisn

## Summary
Page routes must be handled with a static prefix such as `/pages/` until finding better than **match all** pattern.

---

Closes #7708

2021-02-16 11:20 UTC, ilkayilknur approved these changes

2021-02-16 11:20 UTC, ilkayilknur commented on modules/cms-kit/src/Volo.CmsKit.Public.Web/CmsKitPublicWebModule.cs
> +                if (GlobalFeatureManager.Instance.IsEnabled<PagesFeature>())
Can we move the  if check to the top of the `Configure` method? So that we won't call the configure method unnecessarily.

2021-02-16 11:20 UTC, ilkayilknur commented on modules/cms-kit/src/Volo.CmsKit.Public.Web/CmsKitPublicWebModule.cs
> +                    options.Conventions.AddPageRoute("/CmsKit/Pages/Index", @"/pages/{pageUrl:minlength(1)}");
Maybe we should change the route parameter to the `slug.` It will align with the domain.

2021-02-16 11:34 UTC, ilkayilknur requested changes
I accidentally approved the PR.

2021-02-18 06:45 UTC, cotur approved these changes

2021-02-19 09:35 UTC, ilkayilknur approved these changes

2021-02-19 09:35 UTC, merged