Cms Kit - Convert BlogPost CoverImage to Media
abpframework/abp pull request #7963
Opened 2021-03-05 12:12 UTC by enisn

## Summary
This PR removes custom image upload/download logic for BlogPost CoverImage & makes blogpost to use media feature.

2021-03-05 12:36 UTC, cotur approved these changes

2021-03-05 12:38 UTC, cotur requested changes

2021-03-05 12:38 UTC, cotur commented on modules/cms-kit/src/Volo.CmsKit.Public.Web/Pages/Public/CmsKit/Blogs/Index.cshtml
> +}
We can add default dummy image

2021-03-05 12:44 UTC, cotur approved these changes

2021-03-08 09:10 UTC, ilkayilknur approved these changes

2021-03-08 09:11 UTC, ilkayilknur commented
We can merge the PR once @enisn opens DBMigration PR for the commercial template.

2021-03-08 09:29 UTC, merged