Cms Kit - Contents as markdown
abpframework/abp pull request #8191
Opened 2021-03-24 15:33 UTC by enisn

## Summary
This PR provides to store contents as markdown in database and render it as html at public site.

---

- Closes #8185

2021-03-25 11:53 UTC, ilkayilknur requested changes
- We need to open the editor in Markdown mode on edit pages(page/blog post).
- We need to generate the short description from HTML output. 
See
![image](https://user-images.githubusercontent.com/5785927/112468843-d213bc00-8d79-11eb-9b26-df47bcfe9a3b.png)

2021-03-25 13:33 UTC, enisn commented
Fixed, can you review again @ilkayilknur ?

2021-03-26 06:14 UTC, ilkayilknur commented on modules/cms-kit/src/Volo.CmsKit.Admin.Web/Pages/CmsKit/BlogPosts/create.js
> +                    debugger;
remove this.

2021-03-26 06:15 UTC, ilkayilknur approved these changes

2021-03-26 06:15 UTC, merged