Docs - Cms Kit Blogs
abpframework/abp pull request #8861
Opened 2021-04-30 13:52 UTC by enisn

2021-05-07 11:49 UTC, ilkayilknur requested changes

2021-05-07 11:49 UTC, ilkayilknur commented on docs/en/Modules/cms-kit/Blog-System.md
> +CMS kit provides a **Blog** system to to add Blogs & Posts to public website. This section describes the details of the Blog system.
```suggestion
CMS kit provides a **blog** system to add blogs & posts to a public website. This section describes the details of the blog system.
```

2021-05-07 11:49 UTC, ilkayilknur commented on docs/en/Modules/cms-kit/Blog-System.md
> +CMS kit uses the [global feature](https://docs.abp.io/en/abp/latest/Global-Features) system for all implemented features. Commercial startup templates come with all the CMS Kit related features are e
```suggestion
CMS kit uses the [global feature](https://docs.abp.io/en/abp/latest/Global-Features) system for all implemented features. Commercial startup templates come with all the CMS Kit-related features are enabled by default, if you create the solution with the public website option. If you're installing the CMS Kit manually or want to enable the blog feature individually, open the `GlobalFeatureConfigurator` class in the `Domain.Shared` project and place the following code to the `Configure `method.
```

2021-05-07 11:49 UTC, ilkayilknur commented on docs/en/Modules/cms-kit/Blog-System.md
> +- `BlogPost`_(aggregate root)_: Presents Blog Posts by Blogs
```suggestion
- `BlogPost`_(aggregate root)_: Presents blog posts in blogs.
```

2021-05-07 11:49 UTC, ilkayilknur commented on docs/en/Modules/cms-kit/Blog-System.md
> +- `BlogFeauture`:_(aggregate root)_: Presents blog features enabled/disabled state. Such as reactions, ratings, comments etc.
```suggestion
- `BlogFeature`:_(aggregate root)_: Presents blog features enabled/disabled state. Such as reactions, ratings, comments, etc.
```

2021-05-07 11:49 UTC, ilkayilknur commented on docs/en/Modules/cms-kit/Blog-System.md
> +  - `CreateAsync`: Creates a new Blog entity and makes sure slug is used one time.
```suggestion
  - `CreateAsync`: Creates a new `Blog` entity and makes sure slug is used one time.
```

2021-05-07 11:49 UTC, ilkayilknur commented on docs/en/Modules/cms-kit/Blog-System.md
> +  - `UpdateAsync`: Updates existing Blog entity and makes sure slug is used one time.
```suggestion
  - `UpdateAsync`: Updates existing `Blog` entity and makes sure slug is used one time.
```

2021-05-07 11:49 UTC, ilkayilknur commented on docs/en/Modules/cms-kit/Blog-System.md
> +- `BlogAdminAppService` _(implements `IBlogAdminAppService`)_: Implements use cases of Blog Management.
```suggestion
- `BlogAdminAppService` _(implements `IBlogAdminAppService`)_: Implements use cases of blog management.
```

2021-05-07 11:49 UTC, ilkayilknur commented on docs/en/Modules/cms-kit/Blog-System.md
> +- `BlogFeatureAdminAppService` _(implements `IBlogFeatureAdminAppService`)_: Implements use cases of Blog Feature Management.
```suggestion
- `BlogFeatureAdminAppService` _(implements `IBlogFeatureAdminAppService`)_: Implements use cases of blog feature management.
```

2021-05-07 11:49 UTC, ilkayilknur commented on docs/en/Modules/cms-kit/Blog-System.md
> +- `BlogPostAdminAppService` _(implements `IBlogPostAdminAppService`)_: Implements use cases of Blog Post Management.
```suggestion
- `BlogPostAdminAppService` _(implements `IBlogPostAdminAppService`)_: Implements use cases of blog post management.
```

2021-05-07 11:49 UTC, ilkayilknur commented on docs/en/Modules/cms-kit/Blog-System.md
> +- `BlogPostPublicAppService` _(implements `IBlogPostPublicAppService`)_: Implements public blog post displaying operations.
```suggestion
- `BlogPostPublicAppService` _(implements `IBlogPostPublicAppService`)_: Implements use cases of blog posts management on public websites.
```

2021-05-07 11:54 UTC, ilkayilknur commented
Instead of mentioning the Admin UI at the end of the document, we need to mention UI controls.  I already covered the admin UI in the overall document. We don't need to duplicate that content. @enisn

2021-05-10 13:26 UTC, enisn commented
> Instead of mentioning the Admin UI at the end of the document, we need to mention UI controls. I already covered the admin UI in the overall document. We don't need to duplicate that content. @enisn

Blogs don't have any public UI component to be invoked. 

It has only **DefaultBlogPostCommentViewComponent** but it encapsulates **CommentingViewComponent**.

2021-05-12 07:49 UTC, ilkayilknur approved these changes

2021-05-12 07:49 UTC, merged