Allow to customize EF Core mapping of entity and dbContext of an existing module
abpframework/abp pull request #8898
Opened 2021-05-05 09:33 UTC by realLiangshiwei

Resolve https://github.com/abpframework/abp/issues/8863, https://github.com/abpframework/abp/issues/8862

2021-05-11 10:00 UTC, realLiangshiwei commented
See https://github.com/abpframework/abp/issues/8862#issuecomment-838194688

2021-05-28 08:56 UTC, hikalkan requested changes

2021-05-28 08:56 UTC, hikalkan commented on framework/src/Volo.Abp.ObjectExtending/Volo/Abp/ObjectExtending/ObjectExtensionInfo.cs
> +            Type = type;
Checking for null would be good.

2021-05-28 08:56 UTC, hikalkan commented on framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/ObjectExtending/EfCoreObjectExtensionManagerExtensions.cs
> +        public static void ConfigureEfCoreEntityProperties(
Renaming this method (and replacing with another one which does a different thing) is a hidden breaking change which is very dangerous.
I suggest to merge these two methods (`ConfigureEfCoreEntityProperties` and `ConfigureEfCoreEntity`) that performs both entity and property mappings in a single method. This won't be a breaking change and will be more meaningful.

2021-06-03 19:12 UTC, hikalkan approved these changes

2021-06-03 19:12 UTC, merged