Add Simple State Checker document.
abpframework/abp pull request #8899
Opened 2021-05-05 12:06 UTC by maliming

Resolve #8895

2021-05-06 16:24 UTC, hikalkan requested changes

2021-05-06 16:24 UTC, hikalkan commented on docs/en/SimpleStateChecker.md
> +## Built-in state checker
```suggestion
## Built-in State Checkers
```

2021-05-06 16:24 UTC, hikalkan commented on docs/en/SimpleStateChecker.md
> +### Check the state
```suggestion
## Check the state
```

This should not be under "Definition global state checker"

2021-05-06 16:24 UTC, hikalkan commented on docs/en/SimpleStateChecker.md
> +## Definition global state checker.
```suggestion
## Definition Global State Checkers
```

Please use "Title Case" for titles and do not use `.` at the end.

2021-05-06 16:24 UTC, hikalkan commented on docs/en/SimpleStateChecker.md
> +The **state** of some objects may depend on multiple conditions, such as some permissions are required, features need to be enabled, or it is only for special users and roles are available.
```suggestion
The simple state checking system can be used to enable/disable an object based on some dynamic conditions. For example, you can disable a menu item on the user interface, if the current user has not granted for a given permission. The simple state checking system provides a generic way to define and check such conditions.
```

2021-05-07 01:18 UTC, realLiangshiwei approved these changes

2021-05-17 08:57 UTC, hikalkan approved these changes

2021-05-17 08:57 UTC, merged