Document how to add basic theme's source code into the application's solution
abpframework/abp pull request #9307
Opened 2021-06-14 11:33 UTC by yekalkan

Done for Blazor Wasm & MVC.

Related https://github.com/abpframework/abp/issues/8169

2021-06-14 13:53 UTC, hikalkan requested changes

2021-06-14 13:53 UTC, hikalkan commented on docs/en/UI/AspNetCore/Basic-Theme.md
> +You can run the following [ABP CLI](../../CLI.md) command to copy the source code to your solution:
Where we will run this command? Please specify.

2021-06-14 13:54 UTC, hikalkan commented
Send this PR to rel-4.3 branch (if that was a feature already shipped).

2021-06-15 08:22 UTC, yekalkan commented
> Send this PR to rel-4.3 branch (if that was a feature already shipped).

This won't work for 4.3 after we release 4.4

2021-06-16 11:12 UTC, hikalkan approved these changes

2021-06-16 11:12 UTC, merged